add specific db cache for notion
tough-dev-school/education-backend pull request #1695
Opened 2023-06-23 07:02 UTC by da-maltsev

К [задаче](https://3.basecamp.com/5104612/buckets/29069198/todos/6282180568)

Добавил отдельный кеш для ноушена в бд.
Так сразу 2 выигрыша от отдельного кеша:

1.  В дамп не попадут лишние кеши, в тч чувствительные данные
2. Скорость кеша для остальной части приложения не пострадает

2023-06-23 08:45 UTC, f213 commented on src/notion/models.py
> +class NotionCache(models.Model):
```suggestion
class NotionCacheEntry(models.Model):
```
Модель — это одна запись кеша, а не весь кеш целиком

2023-06-23 08:45 UTC, f213 commented on src/notion/models.py
> +    Generated from SQL via createcachetable command
А зачем это? Почему бы просто не завести обычную таблицу?

2023-06-23 08:45 UTC, f213 commented on src/notion/models.py
> +class NotionCache(models.Model):
Кажется лучше наследоваться от нашей обычной TimestampedModel, чтобы можно было в случае отладки найти время создания\обновления записи

2023-06-23 08:45 UTC, f213 commented on src/notion/models.py
> +    cache_key = models.CharField(max_length=255, primary_key=True)
А какой практический смысл в замене привычного primary key на кастомный?

2023-06-23 08:45 UTC, f213 commented on src/notion/models.py
> +        db_table = "notion_cache_table"
Подскажи, зачем нам нестандартное название таблицы?

2023-06-23 08:52 UTC, da-maltsev commented on src/notion/models.py
> +    Generated from SQL via createcachetable command
Не очень понимаю, что значит "обычную таблицу".
 Django для кеша генерирует следующее:
`./manage.py createcachetable --dry-run                                                                               
CREATE TABLE "notion_cache_table" (
    "cache_key" varchar(255) NOT NULL PRIMARY KEY,
    "value" text NOT NULL,
    "expires" timestamp with time zone NOT NULL
);
CREATE INDEX "notion_cache_table_expires" ON "notion_cache_table" ("expires");`

Опираясь на это я сделал модель соответствующую этому SQL, чтобы не запускать отдельную команду.

А что ты предлагаешь?

2023-06-23 08:53 UTC, da-maltsev commented on src/notion/models.py
> +    cache_key = models.CharField(max_length=255, primary_key=True)
Тут я просто следую тому, как джанга генерирует таблицу для кеша
`
CREATE TABLE "notion_cache_table" (
    "cache_key" varchar(255) NOT NULL PRIMARY KEY,
    "value" text NOT NULL,
    "expires" timestamp with time zone NOT NULL
);
CREATE INDEX "notion_cache_table_expires" ON "notion_cache_table" ("expires");`

2023-06-23 08:54 UTC, da-maltsev commented on src/notion/models.py
> +        db_table = "notion_cache_table"
Тут в этом в целом нет необходимости, можно сначала создать миграцию и из неё название вытянуть и указать в Location для кеша.

2023-06-23 09:23 UTC, da-maltsev commented on src/notion/models.py
> +class NotionCache(models.Model):
Попробовал - проблема в том, что если модель не соотвествует по структуре дефолтному SQL выражению джанги для таблицы кеша, то кеш не работает.
Проверил и с наследованием, и просто с добавлением доп полей - просто перестает работать кеширование

2023-06-24 07:58 UTC, f213 commented
Я против любых дополнительных полей для django. Добавить их в проект ничего не стоит, а доработать их потом (или выпилить) стоит адского труда.

К тому же пиклинг наших классов — вообще плохая идея: там есть не только данные, но и код. Представь что будет, если ты положишь в базу экземляр NotionBlockList, а потом выкатишь новую реализиацию, которая как-то влияет на рендеринг? У части юзеров будет крутиться старый код, а у админов — новый, и у тебя не будет никакого способа это отладить.

Давай попробуем упростить это всё. Я вижу два варианта:

1. По сути, NotionPage — это датакласс со списком словарей. То есть нет никаких препятствий, чтобы хранить его в JSONField. Можно посмотреть в сторону [dacite](https://github.com/konradhalas/dacite).
2. Повесить кеш не на уровень наших объектов, а на уровень [запросов в API](https://github.com/tough-dev-school/education-backend/blob/master/src/notion/client.py#L66), тогда вообще не придётся писать никакого доп. кода — достаточно будет просто хранить JSON-поля в БД.

2023-06-24 09:06 UTC, da-maltsev commented
> Я против любых дополнительных полей для django. Добавить их в проект ничего не стоит, а доработать их потом (или выпилить) стоит адского труда.
> 
> К тому же пиклинг наших классов — вообще плохая идея: там есть не только данные, но и код. Представь что будет, если ты положишь в базу экземляр NotionBlockList, а потом выкатишь новую реализиацию, которая как-то влияет на рендеринг? У части юзеров будет крутиться старый код, а у админов — новый, и у тебя не будет никакого способа это отладить.
> 
> Давай попробуем упростить это всё. Я вижу два варианта:
> 
> 1. По сути, NotionPage — это датакласс со списком словарей. То есть нет никаких препятствий, чтобы хранить его в JSONField. Можно посмотреть в сторону [dacite](https://github.com/konradhalas/dacite).
> 2. Повесить кеш не на уровень наших объектов, а на уровень [запросов в API](https://github.com/tough-dev-school/education-backend/blob/master/src/notion/client.py#L66), тогда вообще не придётся писать никакого доп. кода — достаточно будет просто хранить JSON-поля в БД.

Понял, спасибо, что расписал, в чем подводные камни. Запомню на будущее.
Я решил датаклассы в json сохранять. dacite не особо помог, там все равно нужно было бы фабрику писать, так что без доп библиотек добавил простые методы from_dict, as_dict. Теперь кеш хранится в json и его легко обрабатывать.

2023-06-24 17:36 UTC, f213 requested changes
Тесты пока не смотрел, т.к. не устаканилось API

2023-06-24 17:36 UTC, f213 commented on src/notion/cache.py
> +        if cache_entry.expires < timezone.now():
Этот метод называется get. При получении данных из состояния нельзя ничего менять в нём — это сайд-эффект.

Давай выпилим очистку кеша из всего класса. Поскольку у нас cache_key — это уникальный столбец, достаточно использовать [update_or_create](https://docs.djangoproject.com/en/4.2/ref/models/querysets/#update-or-create) в методе set, а в методе get возвращать только непротухшие записи.

2023-06-24 17:36 UTC, f213 commented on src/notion/cache.py
> +    def get_or_set(self, cache_key: str, content: NotionPage | Callable[[], NotionPage], timeout: int = TIMEOUT) -> NotionPage:
Я не вижу большого смысла регулировать таймаут в этом методе. Его можно брать тупо из константы выше. Если очень хочется гибкости — из django settings
```suggestion
    def get_or_set(self, cache_key: str, content: NotionPage | Callable[[], NotionPage]) -> NotionPage:
```

2023-06-24 17:36 UTC, f213 commented on src/notion/cache.py
> +    def get(self, cache_key) -> NotionPage | None:
Ниже мы определяем тип `cache_key` как `str`, а здесь почему-то не указываем. Это специально?

2023-06-24 17:36 UTC, f213 commented on src/notion/cache.py
> +    cache: QuerySet[NotionCacheEntry] = NotionCacheEntry.objects.all()
А какой смысл определять такой кверисет на уровне класса? Почему бы не ходить прямо в модель из мест, где это нужно?

Единственный ответ, который я смог придумать — если его кто-нибудь когда-нибудь будет переопределять. Но я не представляю, чтобы это понадобилось на нашем проекте.

2023-06-24 17:36 UTC, f213 commented on src/notion/cache.py
> +        content = self.content_as_notion_page(content)
Кажется здесь вызов `content_as_notion_page` избыточен — set() и без него превратит `Callable` в `NotionPage`.

А если это так — то и смысл в методе пропадёт: думаю код от этого станет только понятнее, т.к. `content_as_notion_page` ещё и не содержит глагола, от чего плохо читается.

2023-06-24 17:36 UTC, f213 commented on src/notion/cache.py
> +    def notion_page_to_dict(cls, content: NotionPage) -> dict:
Этот метод мне кажется излишним. Если везде дёргать `content.as_dict()` читаемость совершенно не пострадает.

2023-06-24 17:36 UTC, f213 commented on src/notion/cache.py
> +    def dict_to_notion_page(cls, content: dict) -> NotionPage:
Этот — тоже. 

На всякий случай: это и прошлое замечание — это явная вкусовщина, замечания можно игнорить.

2023-06-24 17:36 UTC, f213 commented on src/notion/page.py
> +    def as_dict(self) -> dict:
Меня смущает название этого метода, т.к. оно пересекается c [asdict()](https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict).

Давай переимеуем в `.serialize()` и `.deserialize()`? Или может есть идеи лучше?

2023-06-26 05:16 UTC, da-maltsev commented on src/notion/cache.py
> +        if cache_entry.expires < timezone.now():
Согласен, спасибо, действительно, нет необходимости удалять

2023-06-26 05:17 UTC, da-maltsev commented on src/notion/cache.py
> +    def get(self, cache_key) -> NotionPage | None:
Проглядел. Привык, что обычно mypy ругается, когда сигнатура не типизирована

2023-06-26 05:20 UTC, da-maltsev commented on src/notion/cache.py
> +    cache: QuerySet[NotionCacheEntry] = NotionCacheEntry.objects.all()
В целом, действительно, можно сразу в методах использовать, раз тут такой исключительный кеш для нуошена. А смысл был в том, что я так зависимость на уровне класса определил, ну и в случае, если понадобится в будущем еще для какого-то модуля писать кеш из бд, это послужило бы каркасом для базового класса

2023-06-26 05:22 UTC, da-maltsev commented on src/notion/page.py
> +    def as_dict(self) -> dict:
Меня serialize смущает, тк сериализация может быть и в json, xml, soap, bytes. Поменяю на to_dict()

2023-06-26 05:31 UTC, da-maltsev commented on src/notion/cache.py
> +        content = self.content_as_notion_page(content)
set() не превращает функцию в результат её вызова, поэтому добавил такой метод. Переименую в get_notion_page

2023-06-26 05:40 UTC, f213 commented on src/notion/page.py
> +    def as_dict(self) -> dict:
Может to_json()?

2023-06-26 05:42 UTC, da-maltsev commented on src/notion/page.py
> +    def as_dict(self) -> dict:
Да, давай так, хороший вариант

2023-06-26 05:43 UTC, f213 commented on src/notion/cache.py
> +    cache: QuerySet[NotionCacheEntry] = NotionCacheEntry.objects.all()
Если это случится — значит будет проще написать один базовый класс для двух. Я бы дропнул.

P.S. Посмотрел ещё раз и понял, что меня тут смущает ещё одна вещь — мы вызываем кверисет в момент импорта. Такие вещи часто приводят к странным проблемам — к примеру, если бы мы тут дёргали какой-нибудь условный метод `.not_expired()`, который проверял бы кеш по времени — часы в нём не тикали бы, оставаясь теми же, что были на момент импорта.

2023-06-26 05:43 UTC, f213 commented on src/notion/cache.py
> +    def get(self, cache_key) -> NotionPage | None:
> Привык, что обычно mypy ругается, когда сигнатура не типизирована

Я тоже удивился. Не посмотришь наш проект, почему так происходит?

2023-06-26 05:44 UTC, f213 commented
На всякий случай: пока больше не смотрю код, жду твоего сигнала

2023-06-26 05:45 UTC, da-maltsev commented on src/notion/cache.py
> +    def get(self, cache_key) -> NotionPage | None:
Да, конечно

2023-06-26 05:46 UTC, da-maltsev commented on src/notion/cache.py
> +    cache: QuerySet[NotionCacheEntry] = NotionCacheEntry.objects.all()
Не знал о таком поведении, спасибо за инфу

2023-06-26 08:45 UTC, da-maltsev commented
Внёс правки.
По поводу mypy - не была включена опция disallow-untyped-defs. Попробовал включить - больше 250 ошибок, так что в отдельном ПР добавлю поддержку disallow-untyped-defs и проставлю типы / игноры(если будут ошибки типа несовпадения интерфейса, чтобы в ПР кроме типом ничего не трогать)

2023-06-26 09:56 UTC, da-maltsev commented
Ещё у меня возникла идея - но я не знаю, насколько это необходимо.
Может, сделать таску для селери, чтобы раз в сутки обновлять кеш для всех активных Material?

Как я понимаю, сейчас, вполне возможна ситуация, когда один человек ждет пока материал корректно загрузится, если до него эту страницу не открывал администратор за последние две недели. 

Таска бы была примерно такого типа
```python
def update_cash_notion_material(page_id):
        page = NotionClient().fetch_page_recursively(page_id)
        cache.set(page_id, page)

def update_cash_for_all_active_notion_materials():
    for material in Material.objects.active():
        update_cash_notion_material.delay(material.page_id)
```

2023-06-26 12:56 UTC, f213 commented on src/notion/cache.py
> +        if cache_entry.expires < timezone.now():
А зачем нам проверять expires в коде? Почему бы не вынести это в кверисет?

Это не критично, но читается странно, как будто мы это сделали для чего-то загадочного.

2023-06-26 12:56 UTC, f213 commented on src/notion/cache.py
> +        content = self.get_content_as_notion_page(content)
Этот вызов избыточен

2023-06-26 12:56 UTC, f213 commented on src/notion/tests/test_notion_cache.py
> +    got = cache.get_or_set(cache_entry.cache_key, content=another_page)
Мне кажется здесь вместо `another_page` уместнее было бы использовать `page_from_callable` — так тест был бы больше похож на реальную жизнь.

Заодно было бы клёво проверить, что `page_from_callable` не вызывается, если в кеше уже есть запись

2023-06-26 12:57 UTC, f213 commented
> Может, сделать таску для селери, чтобы раз в сутки обновлять кеш для всех активных Material?

Это отличная идея! Но задача не такая простая — дело в том, что мы платим за количество запросов в ноушен, и бездомно обновлять все материалы не хочется.

Мне кажется уместнее было бы сделать такую команду разовой, а TTL для кеша поставить лет в 5 — так можно будет разово загрузить это в БД, а обновлять потом только те материалы, которые правят админы.

2023-06-26 13:01 UTC, da-maltsev commented
> > Может, сделать таску для селери, чтобы раз в сутки обновлять кеш для всех активных Material?
> 
> Это отличная идея! Но задача не такая простая — дело в том, что мы платим за количество запросов в ноушен, и бездомно обновлять все материалы не хочется.
> 
> Мне кажется уместнее было бы сделать такую команду разовой, а TTL для кеша поставить лет в 5 — так можно будет разово загрузить это в БД, а обновлять потом только те материалы, которые правят админы.

Хорошо. Тогда займусь этой задачей в следующем ПР.

2023-06-26 13:13 UTC, da-maltsev commented on src/notion/cache.py
> +        content = self.get_content_as_notion_page(content)
Убрать отсюда вызов get_content_as_notion_page() и оставить return content, то значение в кеш установится также правильно, но функция вернет Callable,  а если перенести get_content_as_notion_page(content) в return, то если там Callable, она будет вызвана дважды.
То есть тут либо оставить как есть сейчас, либо убрать первый get_content_as_notion_page, но сделать так, чтобы set() возвращала выставленное значение. Я придерживался первого варианта, теперь сделаю по второму тогда

2023-06-28 07:10 UTC, f213 approved these changes

2023-06-28 07:10 UTC, f213 commented on src/notion/cache.py
> +    def get_expires_time(timeout: int = TIMEOUT) -> datetime:
Не понимаю, зачем здесь передавать переменную на вход. Сейчас приложение это никак не использует
```suggestion
    def get_expires_time() -> datetime:
```

2023-06-28 07:10 UTC, f213 commented on src/notion/tests/test_notion_cache.py
> +    pytest.mark.single_thread,
Кажется здесь не имеет смысла использовать single_thread. Раньше он был нужен, чтобы данные не смешивались в общем редисе, а сейчас редиса нет, а в постгресе каждый тест завёрнут в отдельную транзакцию

2023-06-28 07:32 UTC, merged