Notion cache upd command
tough-dev-school/education-backend pull request #1701
Opened 2023-06-28 07:53 UTC by da-maltsev

По мотивам https://github.com/tough-dev-school/education-backend/pull/1695#issuecomment-1607415567

Добавил команду update_notion_cache и поднял TIMEOUT до 5 лет

Команда закидывает в очередь celery таски по апдейту кеша для всех _уникальных и активных_ страницы

2023-06-28 14:36 UTC, f213 requested changes

2023-06-28 14:36 UTC, f213 commented on src/notion/tasks.py
> +        update_cache_notion_material.delay(page_id)
Такая конструкция приведёт нас к моментальному бану в ноушене, т.к. мы одновременно отправим туда несколько тысяч запросов.

Таске нужен рейтлимит, скажем 1 в 10 секунд.

2023-06-28 15:40 UTC, f213 commented on src/notion/cache.py
> +    "cache",
А это зачем?

2023-06-28 15:40 UTC, f213 commented on src/notion/management/commands/update_notion_cache.py
> +        confirm = input("Are you sure you want to update cache for all active Notion materials? (y/n): ")
Давай выпилим всё, что связано с подтверждением отсюда

- Это требует интерактивного терминала. Его вполне может не быть в докер-контейнере
- Если кто-то осилил набрать название команды на клавиатуре — он явно знает, что делает

2023-06-28 15:43 UTC, da-maltsev commented on src/notion/cache.py
> +    "cache",
Чтобы использовать в 
```python
@celery.task
def update_cache_notion_material(page_id):
    page = NotionClient().fetch_page_recursively(page_id)
    cache.set(page_id, page)
```

Можно и не указывать в all конечно, но какой тогда в нем смысл?

2023-06-28 15:54 UTC, da-maltsev commented
@f213 А я могу как-то в продовый контейнер попасть и запустить команду или нужно будет тебя позвать, когда это смерджу?

2023-07-02 15:23 UTC, f213 commented on src/notion/tasks.py
> +def update_cache_notion_material(page_id: str) -> None:
Я бы тут добавил ещё acks_late=True, чтобы если таска падает — она не удалялась из очереди

2023-07-02 15:35 UTC, da-maltsev commented on src/notion/tasks.py
> +def update_cache_notion_material(page_id: str) -> None:
Спасибо, действительно, важный момент

2023-07-04 13:28 UTC, f213 approved these changes

2023-07-04 13:45 UTC, merged