add `default model mixin` with `update` method
tough-dev-school/education-backend pull request #2102
Opened 2023-11-16 19:12 UTC by hnthh

2023-11-17 09:10 UTC, f213 requested changes

2023-11-17 09:10 UTC, f213 commented on src/core/models.py
> +    def update(self: "models.Model", save: bool = True, **kwargs: "Any") -> "models.Model":  # type: ignore[misc]
Зачем здесь type: ignore?

2023-11-17 09:10 UTC, f213 commented on src/core/models.py
> +class DefaultModelMixin:
Мне не нравится, что часть нашего кода для тестироваиня лежит общей базовой модели, а часть — в миксине.

Давай сделаем один миксин, назовём его TestUtilsMixin — всё равно в коде приложения мы нигде это не используем.

2023-11-17 09:10 UTC, f213 commented on src/apps/users/tags/pipeline.py
> +    student.update(tags=list(new_tags))
update() — это метод для тестов. Давай не использовать этот код в приложении — экономия в одной строке текста не стоит уменьшения надёжности.

А ещё мы раньше вызывали в этом месте `save()`, а теперь нет.

2023-11-17 09:10 UTC, f213 commented on src/apps/users/migrations/0005_UserUUID.py
> +        user.update(uuid=uuid.uuid4())
Никогда нельзя использовать код приложения в миграциях. Этой строкой ты сделала свой метод не выпиливаемым — теперь, если его переименовать, миграции перестанут отрабатывать и придётся ещё раз ретроградно их править.

2023-11-17 09:40 UTC, hnthh commented on src/core/models.py
> +class DefaultModelMixin:
Поняла, буду использовать её только в `tests/`-папке. Хотя, по наблюдениям, в других проектах `setattr_and_save`/`update_from_kwargs` использовались не только в тест-коде.

2023-11-17 09:41 UTC, hnthh commented on src/apps/users/tags/pipeline.py
> +    student.update(tags=list(new_tags))
> А ещё мы раньше вызывали в этом месте save(), а теперь нет.

Он вынесен в `.update(…`-функцию.

2023-11-17 09:47 UTC, hnthh commented on src/core/models.py
> +class DefaultModelMixin:
> часть нашего кода для тестироваиня лежит общей базовой модели, а часть — в миксине

Какие-то ещё методы нужно вынести из модели в тест-миксин?

2023-11-17 10:53 UTC, f213 commented on src/core/models.py
> +class DefaultModelMixin:
> Какие-то ещё методы нужно вынести из базовой модели в тест-миксин?

Хотелось бы услышать ответ от тебя

2023-11-17 10:53 UTC, f213 commented on src/apps/users/tags/pipeline.py
> +    student.update(tags=list(new_tags))
> в других проектах setattr_and_save/update_from_kwargs использовались не только в тест-коде.

Это очень плохо, но тот другой проект уже ничем не исправишь.

2023-11-18 16:11 UTC, hnthh commented on src/core/models.py
> +    def update(self: "models.Model", save: bool = True, **kwargs: "Any") -> "models.Model":  # type: ignore[misc]
```bash
src/core/models.py:21: error: The erased type of self "django.db.models.base.Model" is not a supertype of its class "core.models.TestUtilsMixin"  [misc]                            
Found 1 error in 1 file (checked 328 source files)
```

Пробовала исправить по советам [отсюда](https://stackoverflow.com/questions/51930339/how-do-i-correctly-add-type-hints-to-mixin-classes) — не получилось.

2023-11-18 16:34 UTC, hnthh commented on src/core/models.py
> +class DefaultModelMixin:
> Хотелось бы услышать ответ от тебя

Никакие из методов модели (`.copy(…`, `.get_contenttype(…`, `has_field(…`, `.get_label(…`, `.get_foreignkey(…`, `.clear_cached_properties(…`, `_get_cached_property_names(…`) не используются в коде. Удалим?

Если бы они использовались, я бы могла посмотреть, используются ли они где-нибудь, кроме тестов, → вынести в тест-миксин. А пока могу только догадываться об их применительности вне тестов. Как по мне, функция `.update(…` — полезна и я бы её использовала не только в тестах (для большей надёжности можно написать для неё тесты), так что не очень понимаю логику дифференциации функций на тестовые/для основного кода и почему кастомная функция обязательно ненадёжная :-) Потому что если так рассуждать, тогда и сервисы получатся ненадёжными, раз не поставляются джангой…

2023-11-18 16:56 UTC, closed without merging

2023-11-19 16:23 UTC, f213 commented on src/core/models.py
> +class DefaultModelMixin:
> Никакие из методов модели (.copy(…, .get_contenttype(…, has_field(…, .get_label(…, .get_foreignkey(…, .clear_cached_properties(…, _get_cached_property_names(…) не используются в коде. Удалим?

Го!