log successful order property change in the admin area
tough-dev-school/education-backend pull request #2147
Opened 2023-12-12 21:37 UTC by hnthh

Задача в бейскемпе: https://3.basecamp.com/5104612/buckets/29069198/todos/6806491308.

2023-12-13 04:36 UTC, f213 reviewed
И убери пожалуйста незначимые изменения из ПР

2023-12-13 04:36 UTC, f213 commented on Makefile
> +	poetry run autoflake --in-place --remove-all-unused-imports --recursive src tests
Сделай пожалуйста эти изменения в отдельном ПР

2023-12-13 04:36 UTC, f213 commented on src/apps/orders/services/order_paid_setter.py
> +        self.author = get_current_user()
А зачем нам узнавать автора в момент инициализации, а не тогда, когда он нам нужен?

2023-12-13 04:36 UTC, f213 commented on src/apps/orders/services/order_paid_setter.py
> +        if self.author:
Получается, что если мы по каким-то причинам не можем установить автора, мы теряем запись в аудитлоге. Хотя аудитлог — это настолько важная вещь, что кажется лучше бы падать.

Конкретно в этом месте, если мы не знаем автора, можно смело указывать автором студента — ведь если сервис дёргает банк, значит студент сам оплатил себе заказ.

2023-12-13 04:36 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +        if self.author:
Разве у нас в приложении есть место, где мы можем вызвать этот сервис анонимно?

2023-12-13 04:36 UTC, f213 commented on src/core/current_user.py
> +    if user is not None and user.is_authenticated and User.objects.filter(id=user.id).exists():
В какой сиутации возможно, что мы видим юзера, но его нет в базе?

2023-12-13 04:53 UTC, hnthh commented on src/apps/orders/services/order_paid_setter.py
> +        self.author = get_current_user()
@f213, в сервисе-refunder'e автор нужен в двух местах: помимо записи лога — ещё и [здесь](https://github.com/tough-dev-school/education-backend/blob/d093f4a6d616ee737cd93ab9e9218b135783121e/src/apps/orders/services/order_refunder.py#L110), поэтому я вынесла получение автора в общедоступное место, чтобы обе функции имели к нему доступ и не приходилось получать его дважды.

А в этом сервисе просто сделала по аналогии, чтобы был одинаковый интерфейс.

2023-12-13 04:59 UTC, hnthh commented on Makefile
> +	poetry run autoflake --in-place --remove-all-unused-imports --recursive src tests
> Сделай пожалуйста эти изменения в отдельном ПР

Они есть в RP про руфф, так что отдельный, вроде как, не нужен, если руфф доведётся до ума)

Из этого удалю.

2023-12-13 05:14 UTC, f213 commented on src/apps/orders/services/order_paid_setter.py
> +        self.author = get_current_user()
Так вроде интерфейс не изменится, если мы автора будем узнавать только там, где он нужен :-)

2023-12-14 11:07 UTC, hnthh commented on src/apps/orders/services/order_refunder.py
> +        if self.author:
> Разве у нас в приложении есть место, где мы можем вызвать этот сервис анонимно?

А [здесь](https://github.com/tough-dev-school/education-backend/blob/master/src/apps/orders/services/order_refunder.py#L94) для какого случая прописано значение по дефолту?

```python
"refund_author": str(get_current_user() or "unknown"),
```

2023-12-14 11:10 UTC, hnthh commented on src/apps/orders/services/order_refunder.py
> +        if self.author:
Есть тест, который фиксирует, что сервис не падает, если в `current_user` `None`. Значит, такая ситуация возможна?

2023-12-14 11:48 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +        if self.author:
Я думаю лучше сделать, чтобы сервис падал.

2023-12-14 15:16 UTC, hnthh commented on src/apps/orders/services/order_refunder.py
> +        if self.author:
> Я думаю лучше сделать, чтобы сервис падал.

Я попробовала сделать так и упало много тестов. Их можно легко починить, если во всех падающих тестах или сразу модулях использовать `_set_current_user`-фикстуру. Но фиксить слишком много и можно случайно вставить её не там — тогда оголятся пермишены. К примеру, я поставлю эту фикстуру на тест-модуль, а в нём в каком-нибудь тесте тестится, что анон имеет право просматривать главную страницу. Если к этому тесту применить фикстуру, то он тоже пройдёт, но тест уже будет тестить другое — что авторизованный пользователь может просматривать главную страницу и т. д.

Т. к. исправлять много, а в коде я ориентируюсь не супер-пупер, предлагаю, чтобы и лог записывался, и логику не поломать, в автора лога записывать `get_current_user() or self.order.user`.

2023-12-14 15:25 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +        if self.author:
Нет, так не катит. Давай разберёмся, почему тесты падают и придумаем более простое решение, как сделать чтобы order.refund() работал из тестов без текущего юзера в треде.

Проблему, которую ты описала я не до конца понял — а что мешает тебе призывать фикстуру, которая фиксирует результат работы get_current_user() только там, где мы используем рефанды?

2023-12-14 15:32 UTC, hnthh commented on src/apps/orders/services/order_refunder.py
> +        if self.author:
С рефандами довольно просто, падают все те тесты, где `order.refund()` вызывается напрямую. С `.set_paid()` иначе: падают, преимущественно, тесты, в которых `.set_paid()` вызывается не напрямую, а завуалированно; к примеру, [такой](https://github.com/tough-dev-school/education-backend/blob/master/tests/apps/orders/pay_signals/test_setting_order_as_paid_on_stripe_bank_transaction.py#L30) тест починить сложнее, значит, легче ошибиться.

2023-12-14 15:53 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +        if self.author:
> .set_paid() вызывается не напрямую, а завуалированно;

set_paid() мы вполне можем вызывать анонимно — к примеру от основного экварийнга (тинькофф) мы проверяем не собственную аутентификацию DRF, а контрольные суммы запроса на оплату. Я думаю нам стоит чинить только order.refund()

2023-12-14 16:07 UTC, hnthh commented on src/apps/orders/services/order_refunder.py
> +        if self.author:
> set_paid() мы вполне можем вызывать анонимно

Уже нет, потому что сервису `OrderPaidSetter` нужно писать лог, а логу нужен пользователь.

2023-12-14 16:27 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +        if self.author:
Вот [здесь](https://github.com/tough-dev-school/education-backend/pull/2147/files#r1424835739) я просил в таком случае указывать автора заказа.

Подскажи пожалуйста, для чего ты резолвишь мои комментарии, по которым пока нет изменений в ПР? Говорю о комменте по ссылке, или об ещё одном [зарезолвленном комменте](https://github.com/tough-dev-school/education-backend/pull/2147/files/d093f4a6d616ee737cd93ab9e9218b135783121e#diff-1671c35348882b483ad34c785abb3808b4686ccd0d2019ea2cf5eb85dc4ad261), по которому нет ответа.

2023-12-14 16:44 UTC, hnthh commented on src/apps/orders/services/order_refunder.py
> +        if self.author:
> Вот [здесь](https://github.com/tough-dev-school/education-backend/pull/2147/files#r1424835739) я просил в таком случае указывать юзера заказа.

Да, точно ;( Просто это наложилось на вот [это](https://github.com/tough-dev-school/education-backend/pull/2147#discussion_r1426615725) твоё, более актуальное, сообщение.

Ок, для этого сервиса сделаю `get_current_user() or self.order.user`, для рефанда — к каждому падающему тесту или фикстуре с рефандом прицеплю `current_user`.

Насчёт остальных экшнов пока не знаю: до них ещё не дошла.

___

Я резолвлю комменты, когда локально с ними что-то сделала (обычно когда исправила/написала к комменту код и закоммитила) или они больше не актуальны. Мне так удобнее работать над ревью. А как лучше, принято?

2023-12-14 16:57 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +        if self.author:
У нас нет какого-то стандарта на тему резолвинга комментов.

Мне было бы удобнее, если бы ты резолвила только те комменты, по которым есть код в ПР, а в идеале — если я этот код принял. Во втором случае я мог бы сам резолвить свои комменты, если решение мне ок.

Что думаешь об этом?

2023-12-14 17:04 UTC, hnthh commented on src/apps/orders/services/order_refunder.py
> +        if self.author:
Давай так)

Придумаю новый способ не запутываться в комментах.

Твои комменты резолвить не буду, только свои (пояснения к решениям, если в треде нет чьих-нибудь ещё комментов).

2023-12-14 20:21 UTC, hnthh commented on src/core/current_user.py
> +    if user is not None and user.is_authenticated and User.objects.filter(id=user.id).exists():
https://github.com/tough-dev-school/education-backend/assets/67327570/f4f164f9-e927-4e7c-8aa8-1fefaefe95c6

Без этой дополнительной проверки получается так. Причём снова странность в том, что по отдельности поломанные тесты проходят.

2023-12-14 20:33 UTC, hnthh commented on src/apps/orders/services/order_refunder.py
> +            user_id=get_current_user().id,  # type: ignore[union-attr]
Заигнорено вот это:

```bash
src/apps/orders/services/order_refunder.py:73: error: Item "None" of "User | None" has no attribute "id"  [union-attr]
```

2023-12-14 20:36 UTC, hnthh commented on tests/test_order_factory.py
> +    with django_assert_max_num_queries(12):
Здесь появилась запись лога и получение текущего пользователя.

2023-12-15 06:06 UTC, f213 requested changes

2023-12-15 06:06 UTC, f213 commented on src/core/current_user.py
> +    if user is not None and user.is_authenticated and User.objects.filter(id=user.id).exists():
К сожалению, я не смогу это принять — нужно разобраться в причинах, почему твой код падает, а не писать дополнительные if в надсистему.

2023-12-15 06:06 UTC, f213 commented on src/core/tasks/logentry.py
> +def write_admin_log(**kwargs: "Any") -> None:
Почему бы здесь не сделать более специфичную типизацию?

2023-12-15 06:06 UTC, f213 commented on tests/fixtures/core/current_user.py
> +def _set_current_user(user):
```suggestion
def current_user(mocker, user):
  return mocker.patch("core.current_user, get_current_user", return_value=user)
```

Эта фикстура будет гораздо лучше:

1. Она исключает из тестового набора логику работы с тредами, которую нет смысла использовать, если мы её не тестируем
2. Она более универсальна с точки зрения API, т.к. её всегда можно призвать и самому поменять значение current_user

2023-12-15 06:06 UTC, f213 commented on tests/fixtures/core/logentry.py
> +import pytest
Меня смущает название модуля. Он называется `log_entry`, а лежит в нём `write_admin_log`. Почему бы не назвать его так же?

2023-12-15 06:06 UTC, f213 commented on tests/test_order_factory.py
> +    with django_assert_max_num_queries(12):
Я не хотел бы увеличивать количество запросов. Это место используется ОЧЕНЬ много раз в тестах, и +2 запроса на один заказ добавляют не меньше 10 секунд к прогону.

Давай придумаем способ отказаться хотя бы от SELECT-запроса: INSERT в этом месте жрёт меньше, потому что база в тестах работает гораздо быстрее, чем формирование инстанса джанго-модели.

2023-12-15 08:49 UTC, hnthh commented on src/core/tasks/logentry.py
> +def write_admin_log(**kwargs: "Any") -> None:
Заменю кваргс на параметры.

2023-12-15 09:17 UTC, hnthh commented on tests/fixtures/core/current_user.py
> +def _set_current_user(user):
Надо патчить модуль, откуда функция вызывается, а не где она определена. Вот так работает:

```python
import pytest


@pytest.fixture
def current_user(mocker, user):
    return mocker.patch("apps.orders.services.order_refunder.get_current_user", return_value=user)
```

Но это не похоже на кор-фикстуру и для других сервисов нужно писать другие фикстуры.

2023-12-15 10:07 UTC, f213 commented on tests/fixtures/core/current_user.py
> +def _set_current_user(user):
> Надо патчить модуль, откуда функция вызывается, а не где она определена.

Ты проверяла это на нашем коде?

2023-12-15 10:21 UTC, hnthh commented on tests/fixtures/core/current_user.py
> +def _set_current_user(user):
Да, то, что я скинула, рабочий код в нашем коде. Твой не работает ;(

2023-12-15 10:22 UTC, hnthh commented on tests/fixtures/core/current_user.py
> +def _set_current_user(user):
Если поставить точку вместо запятой здесь `current_user, get_current_user` — то тоже работать не будет.

2023-12-18 09:48 UTC, hnthh commented on tests/fixtures/core/current_user.py
> +def _set_current_user(user):
@f213, тогда делаю две отдельные фикстуры: одна для мока в рефанд-сервисе, вторая — для пэйд-сеттер.

2023-12-18 14:25 UTC, hnthh commented on tests/test_order_factory.py
> +    with django_assert_max_num_queries(12):
> и получение текущего пользователя.

То есть, получение `ContentType`.

> Давай придумаем способ отказаться хотя бы от SELECT-запроса

`ContentTypeManager` кеширует получение контент-тайп-объекта:

<img width="930" alt="image" src="https://github.com/tough-dev-school/education-backend/assets/67327570/23a13ebf-5514-4acb-b276-8651cc9f60f8">

Поэтому, если мы дополним тест таким образом —

<img width="757" alt="image" src="https://github.com/tough-dev-school/education-backend/assets/67327570/9430120a-e379-4f07-bdeb-d6e0788ce289">

— он пройдёт.

Это не полное избавление от селекта, но так уже легче. @f213, можем остановиться на этом варианте или думать дальше дальше? Не уверена, что можно получить контент-тайп без захода в базу хотя бы единожды.

2023-12-18 14:56 UTC, hnthh commented on src/core/current_user.py
> +    if user is not None and user.is_authenticated and User.objects.filter(id=user.id).exists():
Эта штука сама пропала, когда в фикстуре `current_user` вместо треда запользовала мок.

2023-12-19 10:49 UTC, f213 commented on tests/fixtures/core/current_user.py
> +def mock_order_refund_service_current_user(mocker, user):
Мне всё ещё не нравится, что фикстура на таком низком уровне знает что-то о высокоуровневых сервисах, для которых она используется.

Давай сделаем ещё один подход. К примеру такой:

```py
from core.current_user import set_current_user, get_current_user

@pytest.fixture
def mock_current_user():
  old_current_user = None

  def _mock_current_user(user):
    old_current_user = get_current_user()
    set_current_user(user)

  yield _mock_current_user

  set_current_user(old_current_user)
```

Немного переживаю про thread safety этого, но почему бы не попробовать.

Что думаешь?

2023-12-19 10:51 UTC, f213 commented on tests/apps/orders/order_shipping/tests_write_success_admin_log.py
> +def test_success_admin_log_created_via_task(order, write_admin_log):
Что можно сломать в приложении, чтобы предыдущий тест не упал, а этот упал?

Если не сможешь придумать — смело дропай: похоже мы здесь тестируем реализацию, а не поведение.

2023-12-19 10:51 UTC, f213 commented on tests/apps/orders/order_shipping/tests_write_success_admin_log.py
> +def test_do_not_break_if_current_user_could_not_be_captured(mocker, order):
Мне не нравится название теста. Как будто мы проверяем крайнюю ситуацию, а на самом деле по бизнесу большинство заказов у нас оплачиваются без current_user.

2023-12-19 10:53 UTC, f213 commented on tests/test_order_factory.py
> +    ContentType.objects.clear_cache()
Зачем это?

2023-12-19 10:54 UTC, f213 commented on tests/test_order_factory.py
> +    with django_assert_num_queries(12):
У нас всё равно остаётся два лишних запроса, просто теперь мы проверяем это более сложным способом. Хочешь ещё подумать, или мне предложить решение?

2023-12-19 11:27 UTC, hnthh commented on tests/test_order_factory.py
> +    ContentType.objects.clear_cache()
Когда этот тест запускается в числе остальных тестов, он может запуститься и запускался с контент-тайпом в кеше, получалось оба раза 11 запросов.

2023-12-19 11:32 UTC, hnthh commented on tests/apps/orders/order_shipping/tests_write_success_admin_log.py
> +def test_success_admin_log_created_via_task(order, write_admin_log):
Можно создавать лог не через таску. Тогда предыдущий не упадёт, потому что лог создастся. Требование было логгировать асинхронно, решила зафиксировать его в тесте, вдруг кто решит вызывать `LogEntry.objects.` напрямую или просто таску без `.delay(` (хотя в таком случае тест пройдёт).

Удаляю?

2023-12-19 11:45 UTC, hnthh commented on tests/apps/orders/order_shipping/tests_write_success_admin_log.py
> +def test_success_admin_log_created_via_task(order, write_admin_log):
Удаляю…

2023-12-19 19:23 UTC, hnthh commented on tests/test_order_factory.py
> +    with django_assert_num_queries(12):
Предложи, пожалуйста, а то запросов становится всё больше (теперь 13).

2023-12-19 19:41 UTC, f213 commented on tests/test_order_factory.py
> +    with django_assert_num_queries(12):
> Возможно, дело в фабрике, которая оторвана от реальности.

Подскажи, а где именно она оторвана? Мне кажется наоборот, она задействует максимальное количество кода из приложения, поэтому и работает медленно.

> Предложи, пожалуйста

Предалагю перенести получение ContentType таску, а таску замокать [здесь](https://github.com/tough-dev-school/education-backend/blob/master/tests/fixtures/core/pause_slow_background_jobs.py), добавив специальный маркер auditlog, который будет включать логирование там, где это надо.

2023-12-20 11:38 UTC, hnthh commented on tests/fixtures/core/current_user.py
> +def mock_order_refund_service_current_user(mocker, user):
Если правильно понимаю, смысл в том, чтобы установленный на один тест или скоуп текущий пользователь не аффектил другие тесты. Тогда можем сделать так?

```python
import pytest

from core import current_user


@pytest.fixture
def _set_current_user(user):
    current_user.set_current_user(user)

    yield

    current_user.unset_current_user()
```

2023-12-20 11:59 UTC, hnthh commented on tests/fixtures/core/current_user.py
> +def mock_order_refund_service_current_user(mocker, user):
https://github.com/kevlened/pytest-parallel#why

Вот какая-то не самая непопулярная, но, кажется, более не разрабатываемая библиотека, которая обещает то, что делает pytest-xdist, только с thread safety.

2023-12-20 14:10 UTC, hnthh commented on tests/fixtures/core/current_user.py
> +def mock_order_refund_service_current_user(mocker, user):
Сейчас в коде есть [фикстура](https://github.com/tough-dev-school/education-backend/blob/b9ef0861ddd57aa9783bea754f8111d395549d09/tests/apps/orders/services/tests_order_refunder.py#L34), которая как раз так пользователя и устанавливает.

2023-12-20 15:23 UTC, hnthh commented on tests/apps/orders/order_shipping/tests_write_success_admin_log.py
> +def test_do_not_break_if_current_user_could_not_be_captured(mocker, order):
<img width="1062" alt="image" src="https://github.com/tough-dev-school/education-backend/assets/67327570/15cacb04-ccc2-460f-95ad-3a36a25b6003">

Я назвала, как было в другом тест-файле…

2023-12-20 18:41 UTC, hnthh commented on src/core/tasks/logentry.py
> +        user_id=user_id,  # type: ignore[arg-type]
Здесь ошибка связана с тем, что `get_current_user()` иногда возвращает `None`, а у `None` нельзя взять `id` в 22-й строке. Я вынесла получение контент-тайпа и пользователя в таску, чтобы в `pause_slow_background_jobs` мокать таску целиком.

Ещё выше ошибки связаны с тем, что я перезаписываю полученные аргументы (`model` в строке 19, `user_id` в строке 22). Мне кажется, не стоит придумывать другие переменные и названия для них, когда переменные можно перезаписать.

2023-12-20 19:58 UTC, hnthh commented on tests/test_order_factory.py
> +    with django_assert_num_queries(12):
> Подскажи, а где именно она оторвана?

Я изначально почему-то решила, что мы чиним не фабрику, а само создание лога в сервисах, чтобы оно было «дешевле», так что пыталась избежать захода в базу при получении `ContentType`, а оно всё никак.

Возникло недоразумение, приношу извинения.

2023-12-21 09:59 UTC, f213 requested changes

2023-12-21 09:59 UTC, f213 commented on src/apps/orders/admin/orders/actions.py
> +    for study in studies:
```suggestion
    for study in studies.iterator():
```

Это действие происходит в основном потоке, почему бы не сделать его быстрее.

2023-12-21 09:59 UTC, f213 commented on src/apps/orders/admin/orders/actions.py
> +    for study in studies:
```suggestion
    for study in studies.iterator():
```

2023-12-21 09:59 UTC, f213 commented on src/apps/orders/services/order_paid_setter.py
> +        user = get_current_user() or self.order.user
```suggestion
        user = get_current_user() or self.order.user  # order may be paid anonymously, we assume customer made it
```

2023-12-21 09:59 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +            app="orders",
Почему бы не использовать здесь привычный по `apps.get_model` синтаксис `orders.Order`?

2023-12-21 09:59 UTC, f213 commented on src/apps/orders/services/order_shipper.py
> +        return "Order shipped without payment" if self.silent else "Order shipped"
По 99% заказов этот сервис вызывается из OrderPaidSetter, то есть лог тут дезинформирует пользователя.

Думаю это как раз то место, где стоит просто логать экшен из админки.

2023-12-21 09:59 UTC, f213 commented on src/core/tasks/logentry.py
> +    content_type_id = ContentType.objects.get_for_model(model).id  # type: ignore[arg-type]
Если выбирать сразу из ContentType, кажется можно обойтись без # type: ignore.

```py
content_type_id = ContentType.objects.get(app_label=app, model=model)
```

Думаю несмотря на то, что джанговская документация рекомендует так не делать, это сильно упростить читаемость, а если когда-нибудь в django решат поменять структуру таблицу с ContentTypes (нет) — мы это заметим.

2023-12-21 09:59 UTC, f213 commented on src/core/tasks/logentry.py
> +    user_id = user_id or get_current_user().id  # type: ignore[assignment, union-attr]
Этот код не будет работать на проде. Таска в селери выполняется вообще в другом контексте — в другом треде и может быть даже на другой тачке. `get_current_user()` там будет всегда возвращать None.

2023-12-21 09:59 UTC, f213 commented on tests/fixtures/core/current_user.py
> +def _set_current_user(user):
Сойдёт. А не хочешь сделать фикстуру _set_current_user() с autouse=True, и чтобы она устаналвивала текущего юзера только если включена марка auditlog? Вряд ли нам понадобится auditlog без текущего юзера.

2023-12-21 17:51 UTC, hnthh commented on src/apps/orders/services/order_shipper.py
> +        return "Order shipped without payment" if self.silent else "Order shipped"
Вынесу логгирование отсюда в экшн админки.

2023-12-21 17:59 UTC, hnthh commented on src/core/tasks/logentry.py
> +    content_type_id = ContentType.objects.get_for_model(model).id  # type: ignore[arg-type]
Так `get_for_model` кешируется, а `get` — не факт. И `app` я из параметров уберу, будет `model`, i. e. `orders.Order`, т. е., чтобы получить название приложения, придётся сплиттить или всё-таки оставить параметр `app`. Плюс дока не рекомендует. Всё это ради `mypy`? 

Всё-таки делаю вышеописанное?

2023-12-21 19:03 UTC, f213 commented on src/core/tasks/logentry.py
> +    content_type_id = ContentType.objects.get_for_model(model).id  # type: ignore[arg-type]
> Так get_for_model кешируется, а get — не факт

А на что это влияет? Пока кажется, что если get не кешируется, то это только облегчит нам тестирование.

2023-12-21 20:37 UTC, hnthh commented on src/apps/orders/services/order_shipper.py
> +        return "Order shipped without payment" if self.silent else "Order shipped"
На всякий случай, после перемещения логгирования в экшн, датаклассовый атрибут `silent` снова не используется в классе. Я не очень понимаю, зачем он во многих местах в коде туда [передаётся](https://github.com/search?q=repo%3Atough-dev-school%2Feducation-backend+ship%28silent%3D&type=code) или, наоборот, [не передаётся](https://github.com/search?q=repo%3Atough-dev-school%2Feducation-backend+ship%28%29&type=code). Может, его пора выпилить в отдельной задаче? Или хотя б оставить какой-нибудь коммент-объяснение.

<img width="719" alt="image" src="https://github.com/tough-dev-school/education-backend/assets/67327570/6750ee21-0828-4c2e-8b8c-fed6c72bc6d1">

2023-12-21 21:48 UTC, hnthh commented on tests/fixtures/core/current_user.py
> +def _set_current_user(user):
> А не хочешь сделать фикстуру _set_current_user() с autouse=True, и чтобы она устаналвивала текущего юзера только если включена марка auditlog?

Хочу, только из-за того что эта фикстура используется [не только](https://github.com/tough-dev-school/education-backend/blob/db5f5bf157064feff8b34f378e8942624f822dbb/tests/apps/orders/services/tests_order_refunder.py#L34) в аудитлог-режиме, я не стала в ней самой делать ветвлений; я сделала иначе, мне кажется, так универсальнее:

<img width="757" alt="image" src="https://github.com/tough-dev-school/education-backend/assets/67327570/80da98db-c56e-4270-bffe-93960329d214">

Это оставляет возможность всё-таки при необходимости использовать `_set_current_user` отдельно от аудитлога.

(на скрине фикстурный модуль `pause_slow_background_jobs.py`, который я переименовала в `markers.py`, чтобы все настройки маркеров были в одном месте, а не стоп тасок в одном, мок функций в другом, подключение фикстур в третьем)

2023-12-21 21:50 UTC, hnthh commented on tests/fixtures/core/current_user.py
> +def _set_current_user(user):
> Вряд ли нам понадобится auditlog без текущего юзера.

Надобится ;)

<img width="707" alt="image" src="https://github.com/tough-dev-school/education-backend/assets/67327570/fb171c9e-372b-4ba8-8035-5f8305c866e4">

Но это крайний случай.

2023-12-21 22:12 UTC, hnthh commented on src/core/tasks/logentry.py
> +    content_type_id = ContentType.objects.get_for_model(model).id  # type: ignore[arg-type]
Пошла смотреть исходники `modeladmin.log_change` и обнаружила реализацию создания лога, отличную от нашей текущей и [без контент тайп](https://github.com/django/django/blob/main/django/contrib/admin/options.py#L966)! (внутри он, правда, всё равно [получается](https://github.com/django/django/blob/3ec15b0bcf03cfa397453910d0087fdb13f02189/django/contrib/admin/models.py#L68))

___

Только применить мы такой же подход не можем, потому что в нашей версии джанги пока нет функции `log_actions`, а есть только `log_action`.

___

Но я к тому, что, несмотря на то что в чистом виде мы контент-тайп в проекте [не получаем](https://github.com/search?q=repo%3Atough-dev-school%2Feducation-backend+ContentType.objects&type=code), в приложении в админке многократно под капотом достаётся закешированный контент-тайп; и какой смысл в этих же экшнах получать контент-тайп не из кеша, а из базы?

2023-12-21 22:17 UTC, hnthh commented on src/apps/orders/services/order_refunder.py
> +            app="orders",
Пока жду ответ по контент-тайпу. Если всё-таки будем получать его через `.get()`, то передавать `orders.Order` в соединенном виде не вижу смысла — всё равно придётся разъединять. А если контент-тайп останется в прежнем виде, то лучше действительно соединить. Но как скажешь. Просто хочу избежать лишних действий в таске вроде сплита или наоборот.

2023-12-22 09:44 UTC, f213 commented on src/core/tasks/logentry.py
> +    content_type_id = ContentType.objects.get_for_model(model).id  # type: ignore[arg-type]
Смысл в том, что внутри селери нам нет смысла беречь машинное время, зато есть смысл поддерживаемость читаемость и уменьшать количество заигноренных ошибок типизации, как и во всём остальном приложении.

2023-12-22 09:44 UTC, f213 commented on tests/fixtures/core/markers.py
> +def _dashamail(mocker, request):
Подскажи, а в чём смысл переименования? Раньше из названия функции можно было понять, чем она занимается, а теперь нет. Это может быть довольно важно при дебаге через  `--setup-plan`, т.к. фикстуры у нас включены в масштабе всего приложения.

Название у модуля тоже плохое — в нём лежат на маркеры, а фикстуры.

2023-12-22 09:44 UTC, f213 commented on src/core/tasks/logentry.py
> +    object_repr: str,
Строковое представление можно получить зная модель и её id. Я бы оставил этот код в таске, чтобы быть поближе к принципу единой ответственности.

Хочется, чтобы потребитель нашего API знал как можно меньше деталей реализации того, как в джанге хранятся логи.

2023-12-22 11:14 UTC, hnthh commented on tests/fixtures/core/markers.py
> +def _dashamail(mocker, request):
> в нём лежат на маркеры, а фикстуры.

Фикстуры есть в неймспейсе:

<img width="308" alt="image" src="https://github.com/tough-dev-school/education-backend/assets/67327570/f0b16c05-c97f-4d20-b461-b7aea8f1b431">

> Подскажи, а в чём смысл переименования?

Теперь в этом модуле не только ставятся на паузу таски. Ещё в нём мокаются функции `write_success_admin_log` сервисов и включаются нужные фикстуры (`_set_current_user`) — всё в зависимости от того, включена марка или нет. Поэтому мне показалось правильным расширить функционал модуля с единственно паузы тасок до настройки маркеров в принципе. Почему бы не сделать фикстуры, которые настраивают маркеры?

2023-12-22 11:18 UTC, hnthh commented on tests/fixtures/core/markers.py
> +def _dashamail(mocker, request):
> Подскажи, а в чём смысл переименования?

Ещё вот в этом комменте рассказывала: https://github.com/tough-dev-school/education-backend/pull/2147/files#r1434539702 (вдруг потерялся).

2023-12-22 13:44 UTC, f213 commented on tests/fixtures/core/markers.py
> +def _dashamail(mocker, request):
Я не вижу принципиальной разницы, хотя на мой вкус твоё решение ухудшает читаемость и затрудняет понимание нашей, итак непростой, структуры тестов. Настаивать не буду.

Единственное, на чём я настаиваю — назови пожалуйста фикстуры понятно.

2023-12-22 13:46 UTC, f213 commented on src/apps/orders/services/order_shipper.py
> +        return "Order shipped without payment" if self.silent else "Order shipped"
Да, его давно пора выпиливать, в OrderShipper он не нужен. Раньше был нужен, пока я не разделил функции, и не сделал, что OrderPaidSetter занимается уведомлениями и интеграциями, а OrderShipper — только выполнением заказов.

2023-12-22 13:47 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +            app="orders",
Я не настаиваю ни на чём кроме того, что эта таска не должна добавлять ни одного запроса к `factory.order(paid=True)`.

2023-12-22 13:48 UTC, f213 commented on tests/apps/orders/order_shipping/tests_write_success_admin_log.py
> +def test_success_admin_log_created_via_task(order, write_admin_log):
Всё ещё актуально.

2023-12-22 13:51 UTC, f213 commented on tests/apps/orders/order_shipping/tests_write_success_admin_log.py
> +def test_do_not_break_if_current_user_could_not_be_captured(mocker, order):
Всё ещё актуально.

2023-12-22 13:51 UTC, f213 commented on src/apps/orders/services/order_paid_setter.py
> +        self.write_success_admin_log()
Всё ещё актуально.

2023-12-22 13:51 UTC, f213 commented on tests/fixtures/core/logentry.py
> +import pytest
Всё ещё актуально.

2023-12-22 13:51 UTC, f213 commented on src/core/tasks/logentry.py
> +    user_id = user_id or get_current_user().id  # type: ignore[assignment, union-attr]
Всё ещё актуально.

2023-12-22 15:37 UTC, hnthh commented on src/apps/orders/services/order_paid_setter.py
> +        self.write_success_admin_log()
> Всё ещё актуально.

Разве?

<img width="505" alt="image" src="https://github.com/tough-dev-school/education-backend/assets/67327570/36b4f11c-a619-4ed8-9055-b34321211809">

<img width="465" alt="image" src="https://github.com/tough-dev-school/education-backend/assets/67327570/ba8a143a-19e5-417f-a2d4-2a51f2373fd6">

2023-12-22 15:38 UTC, hnthh commented on tests/fixtures/core/logentry.py
> +import pytest
Здесь да, хотя помню, что переименовывала; видно, с гитом намудрила, исправлю.

2023-12-22 15:39 UTC, hnthh commented on tests/apps/orders/order_shipping/tests_write_success_admin_log.py
> +def test_success_admin_log_created_via_task(order, write_admin_log):
Этого теста сейчас нет: https://github.com/tough-dev-school/education-backend/pull/2147/files#diff-fd5324116a7411346fe2efcd87300a38527546fd29e073b42e9e9cb9ab476708.

2023-12-22 15:40 UTC, hnthh commented on tests/apps/orders/order_shipping/tests_write_success_admin_log.py
> +def test_do_not_break_if_current_user_could_not_be_captured(mocker, order):
Я переназвала: https://github.com/tough-dev-school/education-backend/pull/2147/files#diff-fd5324116a7411346fe2efcd87300a38527546fd29e073b42e9e9cb9ab476708R36.

2023-12-22 15:40 UTC, hnthh commented on src/core/tasks/logentry.py
> +    user_id = user_id or get_current_user().id  # type: ignore[assignment, union-attr]
Я больше не получаю пользователя в таске: https://github.com/tough-dev-school/education-backend/pull/2147/files#diff-a7c5176900b40af5e8c3d572813ceeac1a10ad9a8ffde5f6039323e7a210312d.

2023-12-22 15:47 UTC, f213 commented on src/core/tasks/logentry.py
> +    user_id = user_id or get_current_user().id  # type: ignore[assignment, union-attr]
А, сорри, это я в комментах запутался :(

2023-12-22 16:08 UTC, hnthh commented on src/apps/orders/services/order_refunder.py
> +            app="orders",
Эта функция (и таска) целиком замокана во всех случаях, кроме тестов аудитлога непосредственно, так что запросы не добавляются.

2023-12-22 16:26 UTC, hnthh commented on src/apps/orders/services/order_shipper.py
> +        return "Order shipped without payment" if self.silent else "Order shipped"
Добавила задачу: https://3.basecamp.com/5104612/buckets/29069198/todos/6877312416.

2023-12-25 06:55 UTC, f213 approved these changes
Два финальных замечания и можно в прод

2023-12-25 06:55 UTC, f213 commented on tests/fixtures/core/markers.py
> +def _auditlog_marker_setup(mocker, request):
Тут всё ещё плохие названия. Раньше их них можно было понять, что они ставят фоновые задачи на паузу, а теперь нет.

2023-12-25 06:55 UTC, f213 commented on src/core/tasks/write_admin_log.py
> +    content_type_id = ContentType.objects.get(app_label=app, model=model.lower()).id
Я не нашёл теста на то, что мы приводим модель к нижнему регистру. Или убери приведение, или напиши тест.

2023-12-25 09:05 UTC, hnthh commented on src/core/tasks/write_admin_log.py
> +    content_type_id = ContentType.objects.get(app_label=app, model=model.lower()).id
> Или убери приведение, или напиши тест.

Убрать нельзя, lowercase обязателен, поэтому напишу тест.

2023-12-25 09:08 UTC, hnthh commented on tests/fixtures/core/markers.py
> +def _auditlog_marker_setup(mocker, request):
> Тут всё ещё плохие названия. Раньше их них можно было понять, что они ставят фоновые задачи на паузу, а теперь нет.

Тогда оставлю названия, какие были:

```python
_pause_dashamail
_pause_tags
```

Аудитлог назову `_pause_auditlog_or_setup_current_user`.

2023-12-25 09:10 UTC, hnthh commented on src/core/tasks/write_admin_log.py
> +    content_type_id = ContentType.objects.get(app_label=app, model=model.lower()).id
> поэтому напишу тест.

Хотя то, что лог создаётся, уже подтверждение тому, что код работает (без `.lower` не работал бы). Так может не нужен тест?

2023-12-25 12:03 UTC, hnthh commented on src/core/tasks/write_admin_log.py
> +    content_type_id = ContentType.objects.get(app_label=app, model=model.lower()).id
Напишу тест, который проверяет, что в `model` можно передать строку в любом регистре и таска отработает, т. к. внутри происходит приведение к нижнему регистру.

2023-12-26 18:12 UTC, f213 approved these changes

2023-12-26 18:12 UTC, f213 commented on tests/fixtures/core/markers.py
> +def _pause_auditlog_or_set_current_user(mocker, request):
Тупое правило: если в названии функции есть and или or — это плохая функция. Меня смущает, что мы, будучи в модуле pause_slow_background_jobs лезем в установку текущего юзера.

Давай не будем автоматически призывать фикстуру `_set_current_user`. Пусть все, кому нужен auditlog, делают это сами.

2023-12-26 18:12 UTC, f213 commented on tests/fixtures/core/markers.py
> +def _auditlog_marker_setup(mocker, request):
Это не ок, ответил ниже.

2023-12-26 18:36 UTC, hnthh commented on tests/fixtures/core/markers.py
> +def _pause_auditlog_or_set_current_user(mocker, request):
> здесь меня смущает, что мы, будучи в модуле pause_slow_background_jobs лезем в установку текущего юзера

Он сейчас `markers.py` называется, название модуля я не откатывала назад 🙃

> Давай не будем автоматически призывать фикстуру `_set_current_user`.

Ок.

2023-12-27 16:04 UTC, merged