handle `ANN` ruff rule
tough-dev-school/education-backend pull request #2228
Opened 2024-03-18 19:15 UTC by hnthh

Я просмотрела заигноренные `ANN`-правила (из `flake8-annotations`) и некоторые ввела в оборот, некоторые оставила в игноре. Они — почти то же, что `mypy`: требуют добавления аннотаций; но `mypy` медленный, а руф — быстрый. Можно, не дожидаясь отчёта майпая, в рамках руфа быстро узнать, где какие аннотации забылись проставиться. В увеличении скорости проверки зааннотированности и есть основная польза, на мой взгляд.

Что касается правил:

1. `ANN001` (https://docs.astral.sh/ruff/rules/missing-type-function-argument/) — оставила для всех директорий, кроме дублирующих локальный игнор майпая;
2. `ANN002` (https://docs.astral.sh/ruff/rules/missing-type-args/) — то же самое;
3. `ANN003` (https://docs.astral.sh/ruff/rules/missing-type-args/) — то же самое;
4. `ANN201` (https://docs.astral.sh/ruff/rules/missing-type-self/) — то же самое;
5. `ANN202` (https://docs.astral.sh/ruff/rules/missing-return-type-private-function/) — то же самое;
6. `ANN204` (https://docs.astral.sh/ruff/rules/missing-return-type-special-method/) — то же самое;
7. `ANN205` (https://docs.astral.sh/ruff/rules/missing-return-type-static-method/) — то же самое;
8. `ANN206` (https://docs.astral.sh/ruff/rules/missing-return-type-static-method/) — то же самое;
9. `ANN101` (https://docs.astral.sh/ruff/rules/missing-type-self/) — оставила в глобальном игноре;
10. `ANN102` (https://docs.astral.sh/ruff/rules/missing-type-self/) — оставила в глобальном игноре.

Колеблюсь насчёт `ANN401` (https://docs.astral.sh/ruff/rules/any-type/): полезное правило, но требует аннотировать аргс и кваргс. Их тип иногда можно конкретизировать, но иногда нет (придётся ставить `noqa`). Оставила в глобальном игноре.

@f213, как настройки?

2024-03-18 19:20 UTC, hnthh commented on src/apps/dashamail/directcrm/events/order_created.py
> +    def __init__(self, order: Order) -> None:
`None` во многих диффах проставился сам в рамках `--unsafe-fixes`. Эти фиксы ещё сами формируют `TYPE_CHECKING` блок: прям импортируют `TYPE_CHECKING` из `typing` и складывают туда импорты.

2024-03-18 19:21 UTC, hnthh commented on src/apps/dashamail/directcrm/events/order_created.py
> +    def __init__(self, order: Order) -> None:
Только он это сделал и в тестовых файлах ;(

2024-03-18 19:30 UTC, hnthh commented
Кстати, [Adam Johnson предлагает](https://adamj.eu/tech/2021/05/07/python-type-hints-use-object-instead-of-any/) аннотировать аргс и кваргс `object` вместо `Any`. Мне нравится идея. Обжект не надо импортировать.

2024-03-22 09:29 UTC, f213 commented on src/core/storages.py
> +    def exists(self, *args, **kwargs) -> bool:  # noqa: ANN002, ANN003
А ты пыталась здесь проставить нормальные типы? Что помешало?

2024-03-22 09:29 UTC, f213 commented on src/core/middleware/real_ip.py
> +def real_ip_middleware(get_response: "Callable[[HttpRequest], HttpResponse]") -> "Callable[[HttpRequest], HttpResponse]":
А зачем здесь кавычки в `Callable`?

2024-03-22 09:29 UTC, f213 commented on src/core/middleware/global_current_user.py
> +def set_global_user(get_response: "Callable[[HttpRequest], HttpResponse]") -> "Callable[[HttpRequest], HttpResponse]":
Подскажи, для чего здесь везде указаны строки вместо типов?

2024-03-22 09:31 UTC, f213 commented
> Кстати, [Adam Johnson предлагает](https://adamj.eu/tech/2021/05/07/python-type-hints-use-object-instead-of-any/) аннотировать аргс и кваргс object вместо Any. Мне нравится идея. Обжект не надо импортировать.

Я против. Мы пишем код не для того, чтобы быстрее его написать, а чтобы его легко было читать. Any — это довольно говорящее название, которое говорит нам, что типа пофиг. Object не говорит вообще ничего. Конечно можно это запомнить, но мне кажется это излишней когнитивной нагрузкой. А если тебе не хочется писать `from typing import  Any` — можно настроить автоимпорты в iDE :-)

2024-03-22 11:32 UTC, hnthh commented on src/core/storages.py
> +    def exists(self, *args, **kwargs) -> bool:  # noqa: ANN002, ANN003
Просто я не знала, что может быть в `*args` и `**kwargs`, но в данном случае всё просто: нужно изменить сигнатуру на ту, что в [оригинале](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3.py#L528).

2024-03-23 14:14 UTC, hnthh commented on src/core/middleware/global_current_user.py
> +def set_global_user(get_response: "Callable[[HttpRequest], HttpResponse]") -> "Callable[[HttpRequest], HttpResponse]":
> Подскажи, для чего здесь везде указаны строки вместо типов?
> А зачем здесь кавычки в `Callable`?

@f213, у этого много причин, вот официальная: https://stackoverflow.com/a/46458497. Но я это делаю ещё и потому что мне нравится, когда блок с импортами не захламлён тем, что было импортировано только для аннотаций: `Callable`, `Any` и проч. — всё это мешает читать код, когда находится в общем блоке. Раньше я руками добавляла это всё в `if TYPE_CHECKING:`-блок. Потом установила линтер, который говорил, каким импортам не место в основном блоке. А теперь установила руф и он формирует `if TYPE_CHECKING:`-блок автоматически. Сравни: на первом видео типы не в кавычках и магия не срабатывает, в отличие от второго:

(**первое**)

https://github.com/tough-dev-school/education-backend/assets/67327570/cb548fee-8b90-4af4-8df0-31521c00d699

(**второе**)

https://github.com/tough-dev-school/education-backend/assets/67327570/186938d8-c638-4c3e-bc77-0c87cae19c87

2024-03-23 14:18 UTC, hnthh commented on src/core/middleware/global_current_user.py
> +def set_global_user(get_response: "Callable[[HttpRequest], HttpResponse]") -> "Callable[[HttpRequest], HttpResponse]":
upd: всмотрелась во второе видео (😅), оказалось, что руф `Callable`, `Any` и остальное, что импортируется из `typing`, не помещает в `if TYPE_CHECKING`. Ну это не страшно, потому что теперь у нас импорты из одного модуля располагаются в одной строке и это не так заметно, как когда:

```python
from typing import TYPE_CHECKING
from typing import Any
from typing import Callable
from typing import typing
```

2024-03-23 14:23 UTC, hnthh commented on src/core/middleware/global_current_user.py
> +def set_global_user(get_response: "Callable[[HttpRequest], HttpResponse]") -> "Callable[[HttpRequest], HttpResponse]":
> строки вместо типов

Может, я буквально восприняла вопрос, но всё равно отвечу: это не просто строки, они так же проверяются `mypy`. Если в них допустить опечатку или поставить неправильный тип, будет ошибка.

2024-03-23 14:26 UTC, hnthh commented
@f213, тогда как поступим с правилом `ANN401` (которое запрещает `Any`)? Может, добавим в правила, а где ну прям совсем никак не проаннотировать, подойдёт нука?

2024-03-23 15:30 UTC, f213 commented
> как поступим с правилом ANN401 (которое запрещает Any)?

Я бы пока не запрещал импортировать Any

2024-03-23 16:07 UTC, f213 commented on src/core/middleware/global_current_user.py
> +def set_global_user(get_response: "Callable[[HttpRequest], HttpResponse]") -> "Callable[[HttpRequest], HttpResponse]":
> у этого много причин, вот официальная: https://stackoverflow.com/a/46458497. 

А где там причина? По ссылке один пользователь stackoverflow объясняет другому пользователю, чем типы в кавычках отличаются от типов без кавычек. Или я чего-то не понимаю.

> Но я это делаю ещё и потому что мне нравится, когда блок с импортами не захламлён тем, что было импортировано только для аннотаций

Звучит, как вкусовщина. Мне, к примеру, не нравится, что по таким аннотациям невозможно прыгать в Go-To-Definition, и приходится много думать, когда сначала импортировал модель под IF-Type-Checking, а потом решил её заюзать не только в типах, но и в коде.

Скажи, можно ли в рафе отключить правило такого форматирования? Не нашёл сходу в документации.

2024-03-23 16:45 UTC, hnthh commented on src/core/middleware/global_current_user.py
> +def set_global_user(get_response: "Callable[[HttpRequest], HttpResponse]") -> "Callable[[HttpRequest], HttpResponse]":
> можно ли в рафе отключить правило такого форматирования? Не нашёл сходу в документации

Можно, надо добавить в игнор эти правила:

<img width="962" alt="image" src="https://github.com/tough-dev-school/education-backend/assets/67327570/d841ca93-5931-4fae-bbc5-f42d88a5ef37">

Добавлю.

2024-03-23 17:46 UTC, hnthh commented on src/core/storages.py
> -    def save(self, *args, **kwargs):
Такой функции нет в оригинальном классе.

2024-03-24 10:20 UTC, f213 requested changes

2024-03-24 10:20 UTC, f213 commented on pyproject.toml
> +    "TCH002",  # move third-party import `{}` into a type-checking block
Мы ни разу не сталкивались с проблемой, которую это и следующее правило решают. И, уверен, не столкнёмся.

Убери их, пожалуйста.

2024-03-24 10:20 UTC, f213 commented on src/core/middleware/global_current_user.py
> +        set_current_user(request.user)  # type: ignore[arg-type]
А почему здесь type: ignore?

2024-03-24 10:20 UTC, f213 commented on src/core/storages.py
> -    def save(self, *args, **kwargs):
Она есть в [базовом сторедже django](https://github.com/django/django/blob/main/django/core/files/storage/base.py#L24), который в свою очередь вызывает [дорогущий _save()](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3.py#L485)

2024-03-24 10:20 UTC, f213 commented on src/core/test/api_client.py
> +        *args: Any,
Скажи, а нам здесь точно нужны `*args` и `**kwargs`? Ни разу не видел, чтобы их кто-то использовал.

2024-03-24 10:20 UTC, f213 commented on src/core/test/api_client.py
> +    def get(self, *args: Any, **kwargs: Any) -> dict | Response:  # type: ignore[override]
Подскажи, а почему в этом и следующих методах у нас type: ignore?

2024-03-24 10:38 UTC, f213 commented on pyproject.toml
> +    "TCH002",  # move third-party import `{}` into a type-checking block
Ой, только сейчас понял, что мы как раз и ставим их в игнор. Спасибо!

2024-04-01 09:37 UTC, f213 approved these changes

2024-04-01 09:52 UTC, merged