Partial refunds
tough-dev-school/education-backend pull request #2230
Opened 2024-03-20 12:21 UTC by paulinenik

OrderRefunder теперь обрабатывает и полный, и частичный возвраты(если указан amount), так, например, можно будет оставить возможность полного возврата в списке

В админку пока не выводила, хочу окнуть изменения сервиса: сейчас я просто храню сумму прошлых возвратов в поле refund_amount заказа, а историю возвратов записываю в LogEntry. 

Вижу два варианта:
1. Реализовать на деталке заказа внизу кнопку "Оформить возврат", где нужно будет ввести сумму возврата, история будет храниться в LogEntry
2. Создать отдельную модель Refund, привязанную к заказу и выводить её на детальной в виде инлайна, тогда историю возвратов можно будет видеть прямо на странице в инлайне и в LogEntry, а refund_amount в заказе в таком случае можно сделать @property

Кажется, что первый вариант реализовать проще, что думаешь?

2024-03-20 18:07 UTC, f213 requested changes

2024-03-20 18:07 UTC, f213 commented on src/apps/orders/migrations/0036_order_refund_amount.py
> +        migrations.AddField(
Мне не нравится такая модель данных. Хочу, чтобы по каждому рефанду была отдельная запись в таблице с рефандами. Кто его сделал, сумма и т.д.

Это даст нам удобный аудитлог и застрахует от ошибок в коде.

2024-03-21 18:28 UTC, f213 reviewed
Так гораздо лучше. Хочу увидеть теперь, как планируешь слать уведомления по частичным рефандам.

2024-03-21 18:28 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +    author: User
А зачем нам здесь это поле, если мы везде пользуемся `get_current_user()`? Добавление доп. поля не сделало код гибче, но добавило кучу букв в тесты — теперь при каждом рефанде надо выдумывать имя автора.

2024-03-21 18:28 UTC, f213 commented on src/apps/orders/models/order.py
> +    def refund_amount(self) -> Decimal:
Я большой противник такого рода полей в модели.

1. Это делает модели толстыми — со временем в слое хранения появляется бизнес-логика.
2. Это сложно читать. Когда мы запрашиваем `order.refund_amount` совершенно непонятно, откуда это прилетело — этот код написан в модели, или может быть он был добавлен через аннотацию менеджера.

Для единообразия я рекомендую делать методы кверисета, которые добавляют нужные поля. В данном случае — OrderQuerySet.with_refund_amount() по аналогии с [Answer.with_crosscheck_count()](https://github.com/tough-dev-school/education-backend/blob/master/src/apps/homework/models/answer.py#L63)

2024-03-21 18:28 UTC, f213 commented on src/apps/tinkoff/dolyame.py
> +    def refund(self, amount: Decimal | None = None) -> None:
А зачем здесь меняем сигнатуру?

2024-03-21 18:28 UTC, f213 commented on src/apps/orders/migrations/0036_Refund.py
> +                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="refunds", to="orders.order", verbose_name="Order")),
Думаю в эту модель стоит дублировать ещё и банк из заказа. Будет проще искать ошибки, если они будут — так мы с гарантией будем знать банк, который был указан в заказе на момент возврата.

В реальной жизни мы не меняем банк у заказа, но тут речь идёт о деньгах, поэтому лучше перестраховаться.

2024-03-21 18:28 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +            OrderUnshipper(order=self.order)()
Чё-т не нашёл теста, в котором видно, что если сумма рефандов становится равна сумме заказа, то заказ аншипится. Или плохо искал?

2024-03-22 08:00 UTC, paulinenik commented on src/apps/tinkoff/dolyame.py
> +    def refund(self, amount: Decimal | None = None) -> None:
Потому что у родительского Bank сигнатура изменилась и линтер ругается, что сигнатуры не совпадают , подумала, что так правильнее, чем повесить type: ignore

![image](https://github.com/tough-dev-school/education-backend/assets/67908968/2ce705ae-e069-4442-807e-e516bb36ba42)

2024-03-22 08:02 UTC, paulinenik commented on src/apps/orders/services/order_refunder.py
> +    author: User
Тоже смутило количество ненужных букв, но глаз замылился и не заметила, что у нас есть get_current_user() для такого, поправлю

2024-03-22 08:05 UTC, paulinenik commented
Уведомления о частичных и полных возвратах отправляются в [одном месте ](url), предлагаю к шаблону кроме изначальной цены добавить [сумму текущего возврата и сколько средств возможно нужно вернуть](url)

2024-03-22 10:37 UTC, paulinenik commented on src/apps/orders/services/order_refunder.py
> +            OrderUnshipper(order=self.order)()
Такой тест [добавила](https://github.com/tough-dev-school/education-backend/pull/2230/files#diff-b057b87bd3fa89b777394e477d1f1b4d5593219a4b97bd672fdc387e3035f48aR293)

2024-03-22 10:51 UTC, paulinenik commented
Сейчас есть всё для частичных возвратов, но полные возвраты в админке по-прежнему работают. ПР уже довольно большой. Если у тебя нет никаких дополнений, я думаю, что мы могли бы слить его уже сейчас. А добавление частичных возвратов в админку я бы сделала в отдельном ПР, как на это смотришь?

Следующие шаги вижу так:

1. Переименовать действие для полных возвратов или убрать его из списка, чтобы было понятно, что это полный возврат.
3. Добавить информацию о возвратах на страницу с деталями заказа.
5. Добавить возможность создания частичного возврата в админке с ограничением в 5 заказов в день.

Раньше я делала такое [так](https://books.agiliq.com/projects/django-admin-cookbook/en/latest/custom_button.html): при нажатии на кнопку происходит переход на страницу с формой, где вводятся нужные данные и редирект на страницу заказа после.

Я понимаю, что кастомайзить админку - боль, но у меня такой опыт есть и если есть вариант лучше - подскажи, что посмотреть, пожалуйста

2024-03-25 06:45 UTC, f213 approved these changes

2024-03-25 06:45 UTC, f213 commented on src/apps/orders/migrations/0036_Refund.py
> +                        verbose_name="User-requested bank string",
Кажется, описание здесь можно было бы сделать более ёмким, что-то вроде `Order bank at the moment of refund`

2024-03-25 06:45 UTC, f213 commented on tests/apps/amocrm/services/order/tests_order_pusher.py
> +def returned_order_with_lead(factory, user, course, amocrm_lead, _set_current_user):
А почему бы здесь не вынести в conftest? Что ломается?

2024-03-25 06:45 UTC, f213 commented on tests/apps/orders/order_queryset/tests_with_refund_amount.py
> +    assert Order.objects.with_refund_amount().get(pk=order.pk).refund_amount == 250
Хочу тест, который проверяет, что в рефанды одного заказа не попадают рефанды других. Понимаю, что это библиотечный код, но тест займёт три строки, зато добавит уверенности.

2024-03-25 06:45 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +    def available_to_refund_amount(self) -> Decimal:
Немного вкусовщины, можно игнорить. А почему это — свойство, а `get_amount_to_refund` — метод?

2024-03-25 06:45 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +        self.amount_to_refund = self.get_amount_to_refund()
Кажется у нас тут появляется [состояние в сервисе](https://3.basecamp.com/5104612/buckets/22530422/messages/5143389486). У нас точно есть хорошие причины для этого?

2024-03-25 06:45 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +        Using this in email.
Сейчас по коду мы используем это не только в почте.

2024-03-25 06:47 UTC, f213 commented
> Я понимаю, что кастомайзить админку - боль, но у меня такой опыт есть и если есть вариант лучше - подскажи, что посмотреть, пожалуйста

Я бы весь код кастомизации спрятал бы в проксимодели. Сделал бы прокси-модель к рефандам, типа `AdminRefund`, выводил бы её в админке заказа как Inline, а при добавлении переопределил бы метод `AdminRefundManager.create()` или форму в админке (забыл, что лучше), чтобы они вместо создания записи в БД вызывали бы OrderRefunder.

Таким образом мы получим вывод всех возвратов по заказу в привычном интерфейсе админки и ноль кастомизаций.

2024-03-25 11:46 UTC, paulinenik commented on tests/apps/amocrm/services/order/tests_order_pusher.py
> +def returned_order_with_lead(factory, user, course, amocrm_lead, _set_current_user):
Вынесу, сначала использовала в pytestmark и внутри фикстур не подхватывалось при рефанде, потестила в контексте с autouse - всё ок

2024-03-25 11:48 UTC, paulinenik commented on src/apps/orders/services/order_refunder.py
> +    def available_to_refund_amount(self) -> Decimal:
Хотела и get_amount_to_refund сделать свойством на самом деле, но поняла, что т.к. результат зависит от записей о возврате, нам важно сохранить значение до процедуры заказа

2024-03-25 11:50 UTC, paulinenik commented on src/apps/orders/services/order_refunder.py
> +        self.amount_to_refund = self.get_amount_to_refund()
Веских нет, оставила для удобства (в моменте) и единообразия(другие данные мы не передаем аргументами ни при записи логов, ни в шаблон письма для админов), поправлю и добавлю в сигнатуры методов

2024-03-25 11:53 UTC, paulinenik commented
@f213 комментарии поправлю чуть позже, а пока вопрос: в сервисе возврата происходит много операций, кажется, что стоит обернуть это всё в transaction.atomic, чтобы при ошибке на любом этапе данные в базе не расходились с реальным положением дел

или это не сделано по какой-то причине?

2024-03-25 12:28 UTC, f213 commented
> или это не сделано по какой-то причине?

2024-03-27 05:12 UTC, f213 reviewed
Я тут чё-то принёс важных замечаний в последний момент :-)

2024-03-27 05:12 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +    If amount is not specified - refund full available to refund amount.
Слушай, я тут подумал, что кажется код был бы гораздо проще, если бы мы сломали API сервиса и требовали всегда указывать сумму возвратов. Мы не так часто в приложении вызываем этот сервис, думаю поменять займёт совсем немного времени.

2024-03-27 05:12 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +    def available_to_refund_amount(self) -> Decimal:
Давай, чтобы не усложнять читаемость сделаем всё геттерами, или всё свойствами. Чтобы у будущих читателей не возникало таких вопросов.

На `@cached_propetry `можно смело забивать — бизнес-логики это не добавляет, а +1 запрос к БД при возвратах никто не заметит. Не заметят даже +10

2024-03-27 05:12 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +    def mark_order_as_not_paid_if_needed(self) -> None:
Я думаю от всей этой логики можно избавиться, как и от поля unpaid. Мы пытались на его основе построить дешборды для возвратов, то так и не сделали. В новой версии приложения записи Refund полностью его заменят.

Давай удалим метод и поле unpaid.

2024-03-27 09:36 UTC, paulinenik commented on src/apps/orders/services/order_refunder.py
> +    def mark_order_as_not_paid_if_needed(self) -> None:
Тогда paid мы не сбрасываем при полном возврате?

Ещё такой вопрос, если мы делаем возврат для ещё не оплаченного заказа (paid=None), то к возврату доступно 0 и в записи о возврате - 0?

2024-03-28 13:36 UTC, paulinenik commented on src/apps/orders/services/order_refunder.py
> +    def mark_order_as_not_paid_if_needed(self) -> None:
UPD: дропнула unpaid, но метод пока оставила, чтобы чистить paid при полном возврате: не уверена, что ничего не сломается, если это убрать (как минимум ломаются тесты с amo)

А вопрос по возврату неоплаченных заказов актуальный, не знаю, может ли быть такой кейс в реальной жизни. Сейчас для таких заказов можно добавлять возвраты до полной стоимости заказа и это кажется мне неверным

2024-03-28 13:51 UTC, paulinenik commented
Я учла все комментарии, а ещё решила админку сделать здесь(через инлайн там действительно добавилось не очень много нового кода, а троттлинг я перенесла прямо в сервис возвратов, и кажется, это наиболее логично)

Смущает только один момент, в админке при мисклике (например, если дважды быстро нажать на сохранить), в инлайнах могут создаваться дубли записей возврата. Для частичного возврата, если сумма может быть возвращена дважды - так и произойдёт, но вероятность такого достаточно мала

2024-03-28 18:37 UTC, f213 commented
> Смущает только один момент, в админке при мисклике (например, если дважды быстро нажать на сохранить), в инлайнах могут создаваться дубли записей возврата. Для частичного возврата, если сумма может быть возвращена дважды - так и произойдёт, но вероятность такого достаточно мала

Давай может и её заблокируем? Можно в тротлинг к примеру добавить логику, что мы можем делать только один возврат в течение 10 секунд.

2024-03-28 18:48 UTC, f213 reviewed
Так, я тут пришёл ещё с одной ВНЕЗАПНОЙ вводной. А по коду мне уже всё нравки, да.

2024-03-28 18:48 UTC, f213 commented on src/apps/orders/admin/orders/admin.py
> +                "fields": ["user", "course", "price", "email", "author", "login_as", "paid", "shipped", "available_to_refund_amount"],
Я не вижу никакого смысла в этом поле для юзера. А какой смысл видишь ты?

2024-03-28 18:48 UTC, f213 commented on src/apps/orders/admin/orders/throttling.py
> -    scope = "order-refund"
Кажется, скоуп стоит выпилить ещё и [отсюда](https://github.com/tough-dev-school/education-backend/blob/060c76f53149b878ab64f1251ef679d87cd033fd/src/core/conf/api.py#L27).

2024-03-28 18:48 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +    def mark_order_as_not_paid_if_needed(self) -> None:
Так, я тут нашёл ещё одну важную проблему. У нас сейчас написана куча дешбордов, в которых мы считаем деньги. К примеру, чтобы посчитать деньги за период, мы берём все заказы, у которых `paid is not null and between period_start and period_end` и делаем `SUM(price * acquiring_percent)`.

Получается, что как только мы перейдём на новую систему возвратов, все дешборды начнут врать, т.к. при создании частичного возврата price меняться не будет.

Я предлагаю добавить денормализацию:

1. При создании `refund` уменьшать order.price на его сумму
2. `paid` при полном рефанде не сбрасывать, чтобы было видно, что заказ когда-то был оплачен. `order.price` при этом делать нулевым.

Что думаешь?

2024-03-29 09:57 UTC, paulinenik commented on src/apps/orders/services/order_refunder.py
> +    def mark_order_as_not_paid_if_needed(self) -> None:
Супер, это позволит упростить код сервиса ещё немного и полностью отказаться от available_to_refund_amount: по price уже будет понятно, сколько можно вернуть

И ещё раз четче сформулирую вопрос: если заказ не был оплачен (paid=None), а мы пытаемся сделать возврат - что происходит? В моем понимании, нам ещё не поступили деньги, а значит мы не можем их вернуть, но должны закрыть доступ к продукту. 

Для таких заказов возврат делается на сумму 0 и всё равно записывается в логах?

2024-04-01 09:32 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +    def mark_order_as_not_paid_if_needed(self) -> None:
> И ещё раз четче сформулирую вопрос: если заказ не был оплачен (paid=None), а мы пытаемся сделать возврат - что происходит? В моем понимании, нам ещё не поступили деньги, а значит мы не можем их вернуть, но должны закрыть доступ к продукту.

Да, всё так.

На самом деле это довольно редкий кейс — заказ может быть `paid=None` и `shipped is not None` только в случае больших b2b-заказов, когда мы допускаем учеников до занятий до поступления оплаты. Не помню ни одного раза, чтобы при этом нужно было оформлять возврат. Но да, лучше сделать.

На всякий случай не забывай, чт `paid` может быть not `None`, а `price=0` — это ученики, бесплатно допущенные до курсов. Туда попадают ранние чтецы или, к примеру, все кого мы отправляем учиться из fands. Вряд ли конечно там будут возвраты, но лучше бы тоже учесть.

2024-04-01 10:06 UTC, paulinenik commented on src/apps/orders/admin/orders/admin.py
> +                "fields": ["user", "course", "price", "email", "author", "login_as", "paid", "shipped", "available_to_refund_amount"],
Если делаем денормализацию, то его нет, убрала

2024-04-04 12:23 UTC, f213 commented on src/apps/orders/models/order.py
> +    def unpaid(self) -> "OrderQuerySet":
Я бы лучше назвал этот метод not_paid, чтобы было не «разоплачено», а «неоплачено»

2024-04-04 12:23 UTC, f213 commented on src/apps/orders/services/order_refunder.py
> +        self.order.save(update_fields=["price"])
```suggestion
        self.order.save(update_fields=["modified", "price"])
```
Кажется иначе мы потеряем обновление поля modified.

2024-04-04 12:23 UTC, f213 commented on src/apps/orders/services/order_refunder.py
>      def do_bank_refund_if_needed(self) -> None:
Кажется этот метод теперь можно просто назвать `do_bank_refund()`

2024-04-04 12:23 UTC, f213 commented on src/apps/orders/services/order_refunder.py
>          if self.order.paid:
А какой смысл сейчас в этой проверке?

2024-04-04 16:43 UTC, paulinenik commented on src/apps/orders/services/order_refunder.py
>          if self.order.paid:
Ты прав, его нет

2024-04-05 19:52 UTC, f213 requested changes

2024-04-05 19:52 UTC, f213 commented on src/apps/orders/models/order.py
> +        return self.filter(Q(paid__isnull=False, price=0) | Q(paid__isnull=True))
Это слабо сообветствует бизнесу. Заказ вполне может быть оплачен за ноль денег — это внутренине заказы для тестирования, или бесплатно допущенные студенты, к примеру из fands.

Подскажи, какой смысл этого изменения?

2024-04-08 09:11 UTC, paulinenik commented on src/apps/orders/models/order.py
> +        return self.filter(Q(paid__isnull=False, price=0) | Q(paid__isnull=True))
Ты прав, меня тогда спутали тестовые данные и мне казалось, что даже у заказов для чтецов и нас устанавливается ненулевая цена

Но ещё меня смутил вот [этот тест](https://github.com/tough-dev-school/education-backend/blob/9ba1b5ef44025bf324b1ebf17cb39222872e3ca6/tests/apps/amocrm/services/order/tests_order_pusher.py#L131), потому что сейчас новым заказам в амо привязывается лид из возвращенных заказов (или не закрытых)

Сейчас если заказы с paid is not None для этой же сделки существуют - новый заказ не отправится в амо, раньше в [это условие](https://github.com/tough-dev-school/education-backend/blob/3a583f05415b6efe256854c1b7efef523e02db97/src/apps/amocrm/services/orders/order_pusher.py#L86) не попадали заказы с возвратами, потому что мы сбрасывали дату платежа, теперь нужно другое условие

Кажется, это важно и чтобы всё было правильно с точки зрения бизнеса, можно учитывать здесь только заказы с ненулевой ценой, вот так:

`if Order.objects.paid().same_deal(order=self.order).filter(amocrm_lead__isnull=False, price__gt=0).exists():  # we have other paid orders for the same deal`

Что думаешь?

2024-04-10 09:08 UTC, f213 commented on src/apps/orders/models/order.py
> +        return self.filter(Q(paid__isnull=False, price=0) | Q(paid__isnull=True))
Согласен!

2024-04-15 11:02 UTC, f213 approved these changes
Мне всё нравки. Готов это смёрджить на проде с живыми деньгами с моей карточки.

Ты же не видишь никаких препятствий?

2024-04-15 12:04 UTC, f213 commented
> Из важного: в админке в списке по-прежнему можно сделать полный возрат, я поправила название действия на "Сделать полный возврат", чтобы не возникло путаницы

Супер!

> так будет окей?

Да, вполне.

Думаю, сегодня я уже не успею, а завтра будем тестить

2024-04-19 15:32 UTC, merged