Case insensitive user email
tough-dev-school/education-backend pull request #601
Opened 2021-11-08 17:54 UTC by metheoryt

Относится к #265

- JWT-аутентификация по case insensitive email
- Переопределено поле `users.User.email`, опускает регистр при всякой фильтрации по полю. Миграции не требует.
- `users.creator.UserCreator` опускает регистр email при создании пользователя, исключая появление юзеров с иными версиями регистра email/username
- Команда django `merge_same_email_users` запускает мерж активных юзеров с дублирующимся email. Выполняется в транзакции

*Я пересоздал ветку, чтобы не было мерж коммитов, и тем самым закрыл предыдущий PR :(*

2021-11-10 13:03 UTC, f213 commented on src/users/tests/management/test_same_email_user_merge.py
> +    assert getattr(bob_a_rel, rel_name) == bob_b
Давай отделим пустой строкой сетап, действие и асёрт.

2021-11-10 13:03 UTC, f213 commented on src/users/tests/management/test_same_email_user_merge.py
> +    assert getattr(rel_b, rel_name) == bob_b
Этот тест и 3 теста выше нарушают паттерн ААА.

2021-11-10 13:03 UTC, f213 commented on src/users/tests/management/test_same_email_user_merge.py
> +def test_target_user_lower_email(bob_a, bob_b, command, mocker: MockerFixture):
Давай разнесём тестовые наборы по разным модулям вместо того, чтобы отделять комментариями — так будет гораздо легче ориентироваться в коде, когда какой-нибудь из тестов упадёт.

2021-11-10 13:03 UTC, f213 commented on src/users/tests/management/test_same_email_user_merge.py
> +    assert bob_b.email == bob_b.email.lower()
Тут опять теряем ААА, нужно отбивать пустой строкой сетап, действие и асёрт.

2021-11-11 11:36 UTC, metheoryt commented on src/users/management/commands/merge_same_email_users.py
> +            .distinct()
В функциональности не потеряем, но этот запрос не такой уж и сложный, плюс отражает над какой коллекцией мы работаем на самом деле. `.all()` хоть и читается просто, в будущем придётся декодить и задавать вопросы "зачем?". Всё ещё хотите заменить?

2021-11-11 11:45 UTC, metheoryt commented on src/users/models.py
> +    def get_prep_value(self, value):
Это нужно для юзер инпута, например когда юзер логинится с почтой, и вводит её не в lowercase. Пример есть здесь:
https://github.com/tough-dev-school/education-backend/blob/dd6c21059943f2bedcf1c0a050094d0ef0b6324d/src/a12n/api/views.py#L27

  Можно было бы делать lower именно в этой строчке, и вроде бы этим покрылись бы 100% нынешних кейсов поиска по email, но я выбрал сделать это в поле модели на перспективу, чтобы не пришлось делать lower везде где нужно искать по email.

2021-11-11 11:49 UTC, metheoryt commented on src/users/tests/management/test_same_email_user_merge.py
> +    assert getattr(rel_b, rel_name) == bob_b
Из-за того что там 2 ассерта? Я могу удалить второй ассерт, первого достаточно.

2021-11-13 17:42 UTC, f213 requested changes

2021-11-13 17:42 UTC, f213 commented on src/users/management/commands/merge_same_email_users.py
> +        # Merging possibly overlapping relations, leaving as is on collision
Зачем тут 20 строк закомментированного кода?

2021-11-13 17:42 UTC, f213 commented on src/users/management/commands/merge_same_email_users.py
> +            .distinct()
Да.

2021-11-13 17:42 UTC, f213 commented on src/a12n/api/views.py
> +class ObtainJSONWebTokenView(CustomObtainJSONWebTokenView):
Я всё ещё не понимаю, какую проблему мы решаем этим кодом.

2021-11-13 17:42 UTC, f213 commented on src/users/models.py
> +    def get_prep_value(self, value):
Давай уберём пожалуйста, я не вижу смысла писать код на будущее, к тому же в месте, где лучше вообще не писать никакую бизнес-логику (в моделях).

2021-11-15 16:47 UTC, f213 commented on src/a12n/api/views.py
> +class ObtainJSONWebTokenView(jwt.BaseJSONWebTokenAPIView):
Я всё ещё не понимаю, какую проблему мы решаем этим кодом.

2021-11-15 16:49 UTC, f213 reviewed
Всё ещё не понимаю, зачем мы трогаем вьюхи получения JWT

2021-11-15 16:49 UTC, f213 commented on src/users/models.py
> +    email = models.EmailField(_('email address'), blank=True)
Подскажи, для чего мы это добавили?

2021-11-15 17:52 UTC, metheoryt commented
> Всё ещё не понимаю, зачем мы трогаем вьюхи получения JWT

Изначально задача - встрять в процесс аутентификации, и делать lowercase почтовому ящику, который передаётся в качестве username. 

Бэкенд аутентификации ищет `User` по точному совпадению `username`, а в БД все username, которые представляют собой почтовый ящик, после миграции будут в lowercase. Пользователь может передавать почтовый ящик в ином регистре, и тогда система не найдёт аккаунт.

Как вариант, чтобы не лезть в jwt, можно вклеиться в бэкенд аутентификации:

https://github.com/tough-dev-school/education-backend/blob/9ef622e52e59dc77c6993c4ef7f25b39c7258891/src/app/conf/auth.py#L9-L13
```python
class ModelBackend(BaseBackend):
    """
    Authenticates against settings.AUTH_USER_MODEL.
    """

    def authenticate(self, request, username=None, password=None, **kwargs):
        if username is None:
            username = kwargs.get(UserModel.USERNAME_FIELD)
        if username is None or password is None:
            return
        try:
            user = UserModel._default_manager.get_by_natural_key(username)
        except UserModel.DoesNotExist:
            # Run the default password hasher once to reduce the timing
            # difference between an existing and a nonexistent user (#20760).
            UserModel().set_password(password)
        else:
            if user.check_password(password) and self.user_can_authenticate(user):
                return user
```
Или в `_default_manager` упомянутый в коде выше, он же `django.contrib.auth.base_user.BaseUserManager`:
```python
class BaseUserManager(models.Manager):

    ...

    def get_by_natural_key(self, username):
        return self.get(**{self.model.USERNAME_FIELD: username})
```

Это решает проблему "Почему я не могу залогиниться в свой аккаунт? - Пожалуйста, вводите адрес почтового ящика в нижнем регистре"

2021-11-16 10:53 UTC, f213 commented
> Это решает проблему "Почему я не могу залогиниться в свой аккаунт? - Пожалуйста, вводите адрес почтового ящика в нижнем регистре"

Клёво, что ты об этом подумал! Но эта проблема гораздо проще решается на фронте, выкатил [фикс](https://github.com/tough-dev-school/lms-frontend/commit/8f23b4bc0d1d9a6d84ce3c81b227a1c45f6b08bc).

2021-11-16 12:25 UTC, metheoryt commented
> Клёво, что ты об этом подумал! Но эта проблема гораздо проще решается на фронте, выкатил [фикс](https://github.com/tough-dev-school/lms-frontend/commit/8f23b4bc0d1d9a6d84ce3c81b227a1c45f6b08bc).

Спасибо! :smile: Я хотел упомянуть про фронт, но потом понял что не знаю насколько легко будет это сделать там. Ревертнул JWT, тесты зелёные, можно пробовать :ok_hand:

2021-11-17 15:24 UTC, f213 commented
Я прогнал команду на живых данных. Нашёл две проблемы:

1. Она падает, если в базе есть неактивные юзеры (это я починил)
2. По итогам работы юзеры мёрджатся, но при этом всё равно в базе остаются имейлы в разном кейсе.

Давай попробуем починить п.2, чтобы не портить наши данные. То есть будем оставлять после мёрджа все имейлы в нижнем регистре.

2021-11-17 16:14 UTC, metheoryt commented
Можно пробовать снова 👍

2021-11-17 17:20 UTC, f213 commented
К сожалению, у нас есть ещё одна проблема. Во время мёрджа пользователей мы делаем старых пользователей неактивными. То есть если у нас был `Suppoer@microsoft.com` и `support@microsoft.com`, то в базе останется два юзера `support@microsoft.com`, но первый из них будет неактивным.

Таким образом мы сломаем беспарольный вход для всех юзеров, т.к. [вот здесь](https://github.com/tough-dev-school/education-backend/blob/master/src/a12n/api/views.py#L27) мы вообще не проверяем признак активности пользователя. Раз уж мы вводим признак неактивности для студентов (раньше мы его использовали только для staff), то надо с этим разобраться — починить вьюху, чтобы смотрела на флаг is_active

2021-11-17 17:58 UTC, metheoryt commented
Ещё это задевает `UserCreator.get()`
https://github.com/tough-dev-school/education-backend/blob/0e4a971e50a550780360a4ea9fb6579560f04c32/src/users/creator.py#L41-L42

2021-11-19 15:15 UTC, f213 reviewed
По коду всё ок, но я, к своему стыду, обнаружил, что на этой ветке ни разу не отработал CI. Я сейчас починил это, и линтер нашёл кучу ошибок.

Пофиксишь их?

2021-11-19 16:33 UTC, metheoryt commented
@f213 готово!

2021-11-21 09:25 UTC, f213 commented on src/a12n/tests/api/tests_request_passwordless_token.py
> +def test_disabled_user_does_not_involved(user, anon, mixer):
```suggestion
def test_disabled_user_with_the_same_email_does_not_break_authentication(user, anon, mixer):
```

2021-11-21 09:27 UTC, f213 approved these changes

2021-11-21 09:35 UTC, merged