Dispatch only the first answer in crosscheck
tough-dev-school/education-backend pull request #855
Opened 2022-03-26 11:29 UTC by igoose1

Dispatching now uses subquery with a distinct by 'author_id' field.
Subquery was necessary as Django raises "NotImplementedError: annotate()
+ distinct(fields) not implemented." when tries to distinct in the main
query.

Solves: #764.

2022-03-28 15:27 UTC, f213 commented on src/homework/tests/cross_check/tests_get_answer_to_check.py
> +def get_and_give_of_the_same_user(dispatcher, answers_of_the_same_user):
Это очень сложная логика для тестов. Давай попробуем переписать без неё.

2022-04-03 22:53 UTC, igoose1 commented
@f213, обновил черновик.

1. Вынес тесты, связанные с кросс-проверкой ответов одного и того же пользователя, в отдельный файл, чтобы имена фикстур стали проще и не нужно было листать смотреть, что они делают;
2. Добавил тест, который проверяет "making sure the **first** answer of each user..." из `AnswerCrossCheckDispatcher.__doc__`.

Я думал над тем, какие еще тесты добавить. Была мысль впихнуть в answers еще ответ от third_user, чтобы явно проверять, что после get(another_user) дается ответ от third_user, но тогда мне не нравится нейминг в src/users/fixtures,py (есть another_user, а есть third_user), а дополнительной уверенности тест не добавит. В итоге, я остановился на двух, потому что свои изменения в PR могу описать двумя утверждениями:

1. Распределять первый ответ, если ученик заслал несколько;
2. Не распределять другие ответы ученика после первого.

И эти утверждения проверяются.

2022-04-05 09:01 UTC, f213 requested changes

2022-04-05 09:01 UTC, f213 commented on src/homework/tests/cross_check/tests_dispatch_answers_of_the_same_user.py
> +        return service.give_answer_to_user(answer, user)
Не совсем понял, какое отношение имеет к нашему тестовому кейсу создание записи AnswerCrossCheck?

Кажется раньше мы просто делали второй Answer, который следовал вслед за первым и проверяли, что он не отдаётся в AnswerCrossCheck, а теперь выполняем какие-то новые манипуляции, которые в реальном мире сервис не делает.

2022-04-09 15:15 UTC, igoose1 commented on src/homework/tests/cross_check/tests_dispatch_answers_of_the_same_user.py
> +        + [mixer.blend('homework.Answer', question=question, author=another_user, parent=None)]
Не знаю, как принято в этом проекте с переносом операторов. Линтеры проходит, значит славно. Если у тебя другое видение, "suggest change", пожалуйста.

2022-04-09 15:15 UTC, igoose1 commented
@f213, привет, обновил PR.

2022-04-10 15:04 UTC, f213 approved these changes

2022-04-10 15:04 UTC, f213 commented on src/homework/tests/cross_check/tests_dispatch_answers_of_the_same_user.py
> +    pytest.mark.repeat(10),  # we have to repeat this test suite because the method does randomizing
А можно подробнее, зачем мы повторяем этот тест?

2022-04-10 16:44 UTC, igoose1 commented on src/homework/tests/cross_check/tests_dispatch_answers_of_the_same_user.py
> +    pytest.mark.repeat(10),  # we have to repeat this test suite because the method does randomizing
@f213, внутри распределятора есть случайность. Если вдруг что-то сломано, может оказаться, что не всегда выдается первый ответ автора.

2022-04-11 09:24 UTC, merged